/* Google Sheets como fuente operativa del Administrador. Firebase queda para Estudiantes e IA. */
(function(window){
  'use strict';
  function sheets(){if(!window.ADSheetsService)throw new Error('ADSheetsService no está disponible.');return window.ADSheetsService;}
  function texto(v){return String(v===null||v===undefined?'':v).trim();}
  function datos(r){return r&&r.data!==undefined?r.data:r||{};}
  function lista(r){return sheets().extraerLista?sheets().extraerLista(r):[];}
  function periodoResultado(r){var d=datos(r);var ps=Array.isArray(d.periodos)?d.periodos:lista(r);var principal=d.principal||ps.find(function(p){return p&&p.principal;})||ps[0]||{};ps=ps.map(function(p){var id=texto(p.id||p.periodoId||p.value);return{id:id,label:texto(p.label||p.periodoLabel||p.nombre||id),activo:p.activo!==false,principal:id===texto(principal.id||principal.periodoId)};});return{principal:{id:texto(principal.id||principal.periodoId),label:texto(principal.label||principal.periodoLabel||principal.nombre||principal.id)},periodos:ps,activos:ps.filter(function(p){return p.activo;}),configApp:{fuentePrincipal:'google-sheets'}};}
  function normalizarCoordinador(item){item=item||{};var carreras=item.carreras||item.carrerasAsignadas||[];if(!Array.isArray(carreras))carreras=String(carreras||'').split(/[,;|\n]+/).map(texto).filter(Boolean);var id=texto(item.id||item.idRegistro||item.coordinadorId||item.nombre);return Object.assign({},item,{id:id,_docId:id,nombre:texto(item.nombre||item.coordinador||item.Nombre||id),telegram:texto(item.telegram||item.Telegram),activo:item.activo!==false&&String(item.estado||'ACTIVO').toUpperCase()!=='INACTIVO',carreras:carreras,fuente:'google-sheets'});}

  function instalarPeriodos(){var s=window.ADPeriodosService;if(!s||s.__soloSheets)return;function todos(){return sheets().enviarGet('LISTAR_PERIODOS_TITULACION',{}).then(periodoResultado);}s.listarTodosLosPeriodos=todos;s.listarPeriodos=function(){return todos().then(function(r){return{principal:r.principal,periodos:r.activos,configApp:r.configApp};});};s.cambiarEstadoPeriodo=function(id,activo){return todos().then(function(r){var ps=r.periodos.map(function(p){return Object.assign({},p,{activo:p.id===id?activo===true:p.activo});});var activos=ps.filter(function(p){return p.activo;});if(!activos.length)throw new Error('Debe existir al menos un período activo.');var principal=activos.find(function(p){return p.principal;})||activos[0];return sheets().enviarPost('GUARDAR_PERIODOS_TITULACION',{periodos:ps,principal:principal,administrador:'administrador'}).then(todos);});};s.__soloSheets=true;}

  function instalarCoordinadores(){var s=window.ADCoordinadoresService;if(!s||s.__soloSheets)return;function listarTodos(){return sheets().enviarGet('LISTAR_COORDINADORES',{incluirInactivos:true}).then(function(r){var cs=lista(r).map(normalizarCoordinador);return{ok:true,total:cs.length,coordinadores:cs,fuente:'google-sheets',fuentePrincipal:'Google Sheets'};});}function obtener(id){return listarTodos().then(function(r){return r.coordinadores.find(function(c){return texto(c.id)===texto(id);})||null;});}function sincronizar(cs,origen){var normal=(Array.isArray(cs)?cs:[]).map(normalizarCoordinador);return sheets().enviarPost('SINCRONIZAR_COORDINADORES',{coordinadores:normal,total:normal.length,reemplazar:true,origen:origen||'administrador'}).then(function(){return{ok:true,total:normal.length,coordinadores:normal,mensaje:'Catálogo guardado en Google Sheets.'};});}s.listarCoordinadores=listarTodos;s.obtenerCoordinador=obtener;s.guardarCoordinador=function(item){item=normalizarCoordinador(item);return sheets().enviarPost('GUARDAR_COORDINADOR',item).then(function(){item.mensaje='Coordinador guardado en Google Sheets.';return item;});};s.cambiarEstado=function(id,activo){return obtener(id).then(function(item){if(!item)throw new Error('No se encontró el coordinador.');item.activo=activo===true;return sheets().enviarPost('CAMBIAR_ESTADO_COORDINADOR',item).then(function(){return item;});});};s.sincronizarCatalogo=sincronizar;s.sincronizarTodosConSheets=function(){return listarTodos().then(function(r){return sincronizar(r.coordinadores,'administrador');});};s.listarFirebase=function(){return Promise.resolve([]);};s.__soloSheets=true;}

  function instalarTitulos(){var s=window.ADTitulosService;if(!s||s.__soloSheets)return;s.listarTitulosBasico=function(limite){return sheets().enviarGet('LISTAR_ENVIOS_POR_CARRERA',{carrera:'',carreras:'',estado:'',limite:limite||1000}).then(lista);};s.__soloSheets=true;}

  function instalarDiagnostico(){var s=window.ADDiagnosticoService;if(!s||s.__soloSheets)return;var original=s.probarFirebase;s.probarFirebase=function(){var fs=window.ADFirebaseService;var c=window.AD_CONFIG&&window.AD_CONFIG.colecciones||{};return Promise.all([fs&&fs.contarColeccion?fs.contarColeccion(c.estudiantes||'Estudiantes').catch(function(){return{total:0};}):Promise.resolve({total:0}),sheets().enviarGet('RESUMEN_ADMINISTRADOR',{}).catch(function(){return{data:{}};}),sheets().enviarGet('LISTAR_PERIODOS_TITULACION',{}),sheets().enviarGet('LISTAR_COORDINADORES',{}),sheets().enviarGet('LISTAR_LOGS',{limite:10}).catch(function(){return{data:{logs:[]}};}),sheets().leerConfiguracion()]).then(function(p){var resumen=datos(p[1]);var per=periodoResultado(p[2]);var coords=lista(p[3]).map(normalizarCoordinador);return{ok:true,proyecto:window.AD_CONFIG.firebaseConfig.projectId,configExiste:true,configApp:{},periodo:{id:per.principal.id,label:per.principal.label,periodosActivos:per.activos.map(function(x){return x.id;}),periodosActivosLabels:per.activos.map(function(x){return x.label;})},sheets:p[5],colecciones:[{nombre:c.estudiantes||'Estudiantes',ok:true,total:Number(p[0].total||0),muestra:[]},{nombre:c.titulos||'titulos',ok:true,total:Number(resumen.totalEnvios||0),muestra:[]},{nombre:c.coordinadores||'titulos_coordinadores',ok:true,total:coords.length,muestra:coords}],logsRecientes:lista(p[4])};}).catch(function(error){if(original)return original.call(s);throw error;});};s.probarSheets=function(){return sheets().probarPing();};s.obtenerLogsRecientes=function(l){return sheets().enviarGet('LISTAR_LOGS',{limite:l||10}).then(lista);};s.__soloSheets=true;}

  function instalar(){instalarPeriodos();instalarCoordinadores();instalarTitulos();instalarDiagnostico();var f=document.getElementById('ad-badge-firebase');if(f)f.textContent='Datos académicos: Firebase';var sh=document.getElementById('ad-badge-sheets');if(sh)sh.textContent='Google Sheets: principal';}
  instalar();
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',instalar);else window.setTimeout(instalar,0);
  window.ADFuentePrincipalPatch={instalar:instalar,version:'2.0.0'};
})(window);
