/* Google Sheets principal para Administrador; Firebase queda como respaldo. */
(function(window,document){
"use strict";
var done={c:false,e:false,a:false,p:false,t:false,d:false},tries=0;
function tx(v){return String(v==null?"":v).trim();}
function nm(v){return tx(v).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function ck(v){return nm(v).replace(/\s+/g,"");}
function ci(v){return tx(v).replace(/\D/g,"");}
function cf(o,n,d){var x=o||{},m={};Object.keys(x).forEach(function(k){m[ck(k)]=k;});for(var i=0;i<n.length;i++){var k=m[ck(n[i])];if(k!==undefined&&x[k]!=null&&tx(x[k]))return x[k];}return d===undefined?"":d;}
function sh(){if(!window.ADSheetsService)throw new Error("El servicio principal no está disponible.");return window.ADSheetsService;}
function data(r){var d=r&&r.data!==undefined?r.data:r;return d&&d.data!==undefined&&!Array.isArray(d.data)&&d.ok===undefined?d.data:(d||{});}
function list(r,a){if(Array.isArray(r))return r;var d=data(r),z;if(Array.isArray(d))return d;if(window.ADSheetsService&&typeof window.ADSheetsService.extraerLista==="function"){z=window.ADSheetsService.extraerLista(r);if(Array.isArray(z)&&z.length)return z;}a=a||["estudiantes","envios","coordinadores","periodos","registros","filas","rows","items","data"];for(var i=0;i<a.length;i++)if(Array.isArray(d[a[i]]))return d[a[i]];return [];}
function per(v){return v&&typeof v==="object"?{id:tx(v.id||v.periodoId||v.periodo||v.label),label:tx(v.label||v.periodoLabel||v.periodo||v.id)}:{id:tx(v),label:tx(v)};}
function match(o,p){p=per(p);var a=[cf(o,["periodoId","PeriodoId","periodo","Período","periodoLabel","PeriodoLabel"]),o&&o.periodoId,o&&o.periodoLabel,o&&o.periodo].map(nm).filter(Boolean),b=[nm(p.id),nm(p.label)].filter(Boolean);return !b.length||a.some(function(v){return b.indexOf(v)>=0;});}
function est(v){v=nm(v).replace(/ /g,"_").toUpperCase();if(v.indexOf("DEVUEL")>=0||v.indexOf("DEVOLUC")>=0)return"DEVUELTO";if(v.indexOf("REEMPLAZ")>=0)return"REEMPLAZADO";if(v.indexOf("APROBAD")>=0)return"APROBADO";if(v.indexOf("NO_ENVIO")>=0||v.indexOf("ELIMIN")>=0||v.indexOf("BORRAD")>=0)return"NO_ENVIO";if(v.indexOf("PENDIENTE")>=0||v.indexOf("ENVIAD")>=0||v.indexOf("SYNC")>=0)return"ENVIADO";return v;}
function normCoord(x,i){x=x||{};var n=tx(cf(x,["nombre","Nombre","coordinador"])),id=tx(cf(x,["id","idRegistro","coordinadorId","_docId"]))||nm(n).replace(/\s+/g,"_"),cr=cf(x,["carreras"],[]);if(!Array.isArray(cr)){try{cr=JSON.parse(tx(cr));}catch(e){cr=tx(cr).split(/[,;\n|]+/).filter(Boolean);}}return Object.assign({},x,{id:id||"c_"+i,_docId:id||"c_"+i,nombre:n||id,telegram:tx(cf(x,["telegram","Telegram"])),activo:cf(x,["activo"],true)!==false&&tx(cf(x,["estado"],"ACTIVO")).toUpperCase()!=="INACTIVO",carreras:cr,fuente:"google-sheets"});}
function coords(){return sh().enviarGet("LISTAR_COORDINADORES",{incluirInactivos:true}).then(function(r){var a=list(r,["coordinadores","registros","filas","rows","items","data"]).map(normCoord).filter(function(x){return x.id&&x.nombre;});return{ok:true,total:a.length,coordinadores:a,fuente:"google-sheets",fuentePrincipal:"Google Sheets"};});}
function installCoords(){var s=window.ADCoordinadoresService;if(!s||done.c)return false;s.listarCoordinadores=coords;s.obtenerCoordinador=function(id){return coords().then(function(r){return r.coordinadores.find(function(x){return tx(x.id||x._docId)===tx(id);})||null;});};s.__fuentePrincipalAplicada=true;done.c=true;return true;}
function nStudent(x){return{cedula:ci(cf(x,["numeroIdentificacion","cedula","identificacion"])),nombre:tx(cf(x,["Nombres","nombres","Nombre","nombre","estudiante"])),carrera:tx(cf(x,["NombreCarrera","nombreCarrera","Carrera","carrera"])),codigoCarrera:tx(cf(x,["CodigoCarrera","codigoCarrera"])),celularOriginal:tx(cf(x,["Celular","celular","Telefono","Teléfono","WhatsApp","whatsapp"])),periodoId:tx(cf(x,["periodoId","PeriodoId","ultimoPeriodoId","periodo"])),periodoLabel:tx(cf(x,["periodoLabel","PeriodoLabel","periodoTexto","PeriodoTexto","periodo"])),raw:x||{}};}
function phone(v){var n=tx(v).replace(/\D/g,"");if(n.indexOf("00593")===0)n=n.slice(2);if(n.indexOf("5930")===0&&n.length===13)n="593"+n.slice(4);if(n.charAt(0)==="0"&&n.length===10)n="593"+n.slice(1);else if(n.charAt(0)==="9"&&n.length===9)n="593"+n;return/^5939\d{8}$/.test(n)?n:"";}
function nReg(x,h){return{cedula:ci(cf(x,["cedula","numeroIdentificacion","identificacion"])),periodoId:tx(cf(x,["periodoId","PeriodoId","periodo"])),periodoLabel:tx(cf(x,["periodoLabel","PeriodoLabel","periodoTexto","periodo"])),estado:est(cf(x,["estadoFinal","estado","estadoProceso","estadoNuevo"])),titulo1:tx(cf(x,["titulo1","Titulo1","propuesta1"])),titulo2:tx(cf(x,["titulo2","Titulo2","propuesta2"])),titulo3:tx(cf(x,["titulo3","Titulo3","propuesta3"])),tituloPreferido:tx(cf(x,["tituloPreferidoTexto","tituloPreferido","preferido","tituloSeleccionado","tituloElegido"])),tituloAprobado:tx(cf(x,["tituloAprobado","tituloaprobado","tituloFinal","tituloCorregido"])),coordinador:tx(cf(x,["coordinador","coordinadorNombre"])),comentario:tx(cf(x,["comentarioCoordinador","comentario","observacion","motivo"])),fechaEnvio:tx(cf(x,["fechaenviotitulos","fechaEnvioTitulos","fechaEnvio","creadoEn"])),fechaRevision:tx(cf(x,["fechaRevision","fechaResolucion","actualizadoEn"])),hoja:h,raw:Object.assign({},x,{_origenHoja:h})};}
function regs(p){p=per(p);var q=[sh().enviarGet("LISTAR_ENVIOS_POR_CARRERA",{hoja:"Envios",carreras:"",carrera:"",estado:"",incluirTodos:true,periodo:p.id||p.label}),sh().enviarGet("LISTAR_ENVIOS_COORDINADOR",{hoja:"Envios",carreras:"",estado:"",incluirTodos:true,periodo:p.id||p.label}),sh().enviarGet("LISTAR_ENVIOS_COORDINADOR",{hoja:"Resoluciones",carreras:"",estado:"",incluirTodos:true,periodo:p.id||p.label})];return Promise.allSettled(q).then(function(rs){var out=[],ok=0,er=[];rs.forEach(function(r,i){if(r.status==="fulfilled"){ok++;list(r.value,["envios","registros","filas","rows","items","data"]).forEach(function(x){var z=nReg(x,i===2?"Resoluciones":"Envios");if(z.cedula)out.push(z);});}else er.push(r.reason);});if(!ok)throw(er[0]||new Error("No fue posible consultar los registros principales."));return out;});}
function base(p){p=per(p);return sh().enviarGet("LISTAR_BASE_ESTUDIANTES",{periodo:p.id||p.label,incluirTodos:true}).then(function(r){return list(r,["estudiantes","registros","filas","rows","items","data"]).map(nStudent).filter(function(x){return x.cedula&&match(x,p);});});}
function choose(a,p,h){a=(a||[]).filter(function(x){return x.hoja===h&&match(x,p);});return a.length?a[a.length-1]:null;}
function detail(e,r){var s=est((r&&r.estado)||(e&&e.estado)||(e?"ENVIADO":"NO_ENVIO")),d={titulo1:e&&e.titulo1||"",titulo2:e&&e.titulo2||"",titulo3:e&&e.titulo3||"",tituloPreferido:e&&e.tituloPreferido||r&&r.tituloPreferido||"",tituloAprobado:r&&r.tituloAprobado||e&&e.tituloAprobado||"",tituloaprobado:r&&r.tituloAprobado||e&&e.tituloAprobado||"",coordinador:r&&r.coordinador||e&&e.coordinador||"",coordinadorNombre:r&&r.coordinador||e&&e.coordinador||"",comentario:r&&r.comentario||e&&e.comentario||"",comentarioCoordinador:r&&r.comentario||e&&e.comentario||"",fechaEnvio:e&&e.fechaEnvio||"",fechaRevision:r&&r.fechaRevision||e&&e.fechaRevision||"",estado:s,estadoNuevo:s,raw:r&&r.raw||e&&e.raw||{}};d.tienePropuestas=!!(d.titulo1||d.titulo2||d.titulo3);d.propuestasCompletas=!!(d.titulo1&&d.titulo2&&d.titulo3);d.tieneResolucion=!!(d.tituloAprobado||d.coordinador||d.comentario||d.fechaRevision||["APROBADO","REEMPLAZADO","DEVUELTO"].indexOf(s)>=0);return d;}
function installStudents(){var s=window.ADEstudiantesService;if(!s||done.e)return false;var old=typeof s.cargar==="function"?s.cargar.bind(s):null;s.cargar=function(p){var backup=old?old(p).catch(function(){return{estudiantes:[]};}):Promise.resolve({estudiantes:[]});return Promise.all([regs(p),base(p).catch(function(){return[];}),backup]).then(function(z){var rr=z[0],bb=z[1],bk=z[2],roster=bb.length?bb:(bk.estudiantes||[]).map(function(x){return{cedula:ci(x.cedula),nombre:tx(x.nombre),carrera:tx(x.carrera),codigoCarrera:tx(x.codigoCarrera),celularOriginal:tx(x.celularOriginal||x.celular),periodoId:tx(x.periodoId),periodoLabel:tx(x.periodoLabel),raw:x.rawEstudiante||{}};}),idx={};rr.forEach(function(x){(idx[x.cedula]=idx[x.cedula]||[]).push(x);});var es=roster.filter(function(x){return x.cedula&&match(x,p);}).map(function(x){var a=idx[x.cedula]||[],e=choose(a,p,"Envios"),r=choose(a,p,"Resoluciones"),d=detail(e,r),st=e||r?d.estado:"NO_ENVIO";if(st==="NO_ENVIO")d=detail(null,null);return{cedula:x.cedula,nombre:x.nombre,carrera:x.carrera,codigoCarrera:x.codigoCarrera,celular:phone(x.celularOriginal),celularOriginal:x.celularOriginal,periodoId:x.periodoId,periodoLabel:x.periodoLabel,estado:st,registroIncompleto:!!(e&&!d.propuestasCompletas&&!d.tieneResolucion),titulo:d,historial:null,revision:d,detalle:d,rawEstudiante:x.raw,fuente:"google-sheets"};}).sort(function(a,b){return(a.nombre||a.cedula).localeCompare(b.nombre||b.cedula,"es");});return{ok:true,periodo:p,estudiantes:es,total:es.length,sheetsDisponible:true,fuentePrincipal:"Google Sheets",rosterDesdePrincipal:bb.length>0};});};s.__fuentePrincipalAplicada=true;done.e=true;return true;}
function payload(item,mot){var d=item&&(item.detalle||item.titulo||item.revision)||{};return{cedula:ci(item&&item.cedula),numeroIdentificacion:ci(item&&item.cedula),periodo:tx(item&&(item.periodoId||item.periodoLabel)),periodoId:tx(item&&item.periodoId),periodoLabel:tx(item&&item.periodoLabel),estudiante:tx(item&&item.nombre),nombres:tx(item&&item.nombre),carrera:tx(item&&item.carrera),coordinador:"Administrador",estadoFinal:"DEVUELTO",estado:"DEVUELTO",tituloElegido:tx(d.tituloPreferido||d.titulo1),preferido:tx(d.tituloPreferido||d.titulo1),observacion:tx(mot),comentario:tx(mot),motivo:tx(mot),administrador:(window.AD_CONFIG&&window.AD_CONFIG.administrador)||"administrador",fechaResolucion:new Date().toISOString(),origen:"administrador"};}
function installActions(){var s=window.ADEstudiantesActionsService;if(!s||done.a)return false;var od=s.devolverTitulos&&s.devolverTitulos.bind(s),oe=s.eliminarTitulos&&s.eliminarTitulos.bind(s);s.tieneDocumentoActivo=function(i){var d=i&&(i.detalle||i.titulo)||{};return!!(i&&i.estado!=="NO_ENVIO"&&(d.titulo1||d.titulo2||d.titulo3||(d.raw&&d.raw._origenHoja)));};s.devolverTitulos=function(i,m){var p=payload(i,m);if(!p.cedula)return Promise.reject(new Error("No se pudo identificar al estudiante."));return sh().enviarPost("GUARDAR_RESOLUCION",p).then(function(r){return od?od(i,m).then(function(b){return{ok:true,principal:r,respaldo:b};}).catch(function(e){return{ok:true,principal:r,respaldo:false,advertenciaRespaldo:e.message||String(e)};}):{ok:true,principal:r,respaldo:false};});};s.eliminarTitulos=function(i,m){var p=payload(i,m);if(!p.cedula)return Promise.reject(new Error("No se pudo identificar al estudiante."));return sh().enviarPost("ADMIN_ELIMINAR_TITULOS",p).then(function(r){return oe?oe(i,m).then(function(b){return{ok:true,principal:r,respaldo:b};}).catch(function(e){return{ok:true,principal:r,respaldo:false,advertenciaRespaldo:e.message||String(e)};}):{ok:true,principal:r,respaldo:false};});};s.__fuentePrincipalAplicada=true;done.a=true;return true;}
function normPeriods(r,b){var d=data(r),a=list(d,["periodos","registros","filas","rows","items","data"]),m={},out=[];a.forEach(function(x){var p=per(x);if(!p.id||m[nm(p.id)])return;m[nm(p.id)]=1;out.push({id:p.id,label:p.label||p.id,activo:x.activo!==false,principal:x.principal===true,origen:"google-sheets"});});((b&&b.periodos)||[]).forEach(function(x){var p=per(x);if(!p.id||m[nm(p.id)])return;m[nm(p.id)]=1;out.push({id:p.id,label:p.label||p.id,activo:x.activo!==false,principal:false,origen:"firebase-respaldo"});});var pr=per(d.principal||d.periodoPrincipal||{});if(!pr.id){var q=out.find(function(x){return x.principal;})||out[0]||{};pr=per(q);}out.forEach(function(x){x.principal=nm(x.id)===nm(pr.id);});return{principal:{id:pr.id,label:pr.label||pr.id},periodos:out,activos:out.filter(function(x){return x.activo;}),configApp:{fuentePrincipal:"google-sheets"}};}
function installPeriods(){var s=window.ADPeriodosService;if(!s||done.p)return false;var ol=s.listarTodosLosPeriodos&&s.listarTodosLosPeriodos.bind(s),oc=s.cambiarEstadoPeriodo&&s.cambiarEstadoPeriodo.bind(s);s.listarTodosLosPeriodos=function(){var b=ol?ol().catch(function(){return{periodos:[]};}):Promise.resolve({periodos:[]});return Promise.all([sh().enviarGet("LISTAR_PERIODOS_TITULACION",{}),b]).then(function(z){return normPeriods(z[0],z[1]);});};s.listarPeriodos=function(){return s.listarTodosLosPeriodos().then(function(r){return{principal:r.principal,periodos:r.activos,configApp:r.configApp};});};s.cambiarEstadoPeriodo=function(id,ac){return s.listarTodosLosPeriodos().then(function(r){var ps=r.periodos.map(function(x){return{id:x.id,label:x.label,activo:x.id===id?ac===true:x.activo,principal:x.principal};}),pr=r.principal;if(!ps.some(function(x){return x.id===id;}))throw new Error("El período seleccionado no existe.");if(!ps.some(function(x){return x.activo;}))throw new Error("Debe existir al menos un período activo.");if(!ps.some(function(x){return x.activo&&x.id===pr.id;}))pr=ps.find(function(x){return x.activo;});return sh().enviarPost("GUARDAR_PERIODOS_TITULACION",{periodos:ps,principal:pr,administrador:(window.AD_CONFIG&&window.AD_CONFIG.administrador)||"administrador",fecha:new Date().toISOString()}).then(function(){return oc?oc(id,ac).catch(function(){return null;}):null;}).then(function(){return{principal:pr,periodos:ps,activos:ps.filter(function(x){return x.activo;}),configApp:{fuentePrincipal:"google-sheets"}};});});};s.__fuentePrincipalAplicada=true;done.p=true;return true;}
function installTitles(){var s=window.ADTitulosService;if(!s||done.t)return false;s.buscarEstudiantePorCedula=function(v){var c=ci(v);if(!c)return Promise.resolve(null);return sh().enviarGet("CONSULTAR_ESTUDIANTE",{cedula:c,numeroIdentificacion:c}).then(function(r){var d=data(r);return d.estudiante||d.registro||d.data||d||null;});};s.listarTitulosBasico=function(){return regs(null).then(function(a){return a.filter(function(x){return x.hoja==="Envios";}).map(function(x){return x.raw||x;});});};s.__fuentePrincipalAplicada=true;done.t=true;return true;}
function dash(){if(!window.ADSheetsService)return Promise.resolve(false);return Promise.allSettled([sh().enviarGet("LISTAR_BASE_ESTUDIANTES",{incluirTodos:true}),sh().enviarGet("LISTAR_ENVIOS_POR_CARRERA",{hoja:"Envios",carreras:"",carrera:"",estado:"",incluirTodos:true}),sh().enviarGet("LISTAR_COORDINADORES",{incluirInactivos:true}),sh().enviarGet("LISTAR_PERIODOS_TITULACION",{})]).then(function(z){function set(id,v){var e=document.getElementById(id);if(e)e.textContent=String(v);}function total(i,a){return z[i].status==="fulfilled"?list(z[i].value,a).length:0;}var pd=z[3].status==="fulfilled"?data(z[3].value):{},pr=per(pd.principal||pd.periodoPrincipal||{});set("ad-kpi-titulos",total(1,["envios","registros","filas","rows","items","data"]));set("ad-kpi-coordinadores",total(2,["coordinadores","registros","filas","rows","items","data"]));set("ad-kpi-carreras","Datos principales");if(pr.id){set("ad-kpi-periodo",pr.label||pr.id);set("ad-kpi-periodo-id",pr.id);}set("ad-badge-sheets","Google Sheets: principal");set("ad-badge-firebase","Firebase: respaldo");done.d=true;return true;});}
function install(){try{installCoords();}catch(e1){console.error(e1);}try{installStudents();}catch(e2){console.error(e2);}try{installActions();}catch(e3){console.error(e3);}try{installPeriods();}catch(e4){console.error(e4);}try{installTitles();}catch(e5){console.error(e5);}if(window.ADSheetsService&&!done.d)dash().catch(function(e){console.error(e);});}
function start(){install();var timer=setInterval(function(){tries++;install();if((done.c&&done.e&&done.a&&done.p&&done.t)||tries>240)clearInterval(timer);},250);document.addEventListener("click",function(ev){if(ev.target&&ev.target.closest&&ev.target.closest("#ad-btn-recargar-dashboard,#ad-btn-probar-sheets"))setTimeout(function(){dash().catch(function(){});},500);},true);window.addEventListener("ad:vista-cambiada",function(ev){if(ev.detail&&ev.detail.id==="ad-seccion-estado")dash().catch(function(){});});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
window.ADFuentePrincipalPatch={instalar:install,actualizarDashboard:dash,consultarRegistros:regs,consultarBase:base};
})(window,document);
