/* Servicio administrativo seguro para Google Sheets mediante Cloudflare. */
(function(window){
  'use strict';
  function texto(v){return String(v===null||v===undefined?'':v).trim();}
  function numero(v,f){var n=Number(v);return Number.isFinite(n)?n:Number(f||0);}
  function esLocal(){var h=texto(window.location&&window.location.hostname).toLowerCase();return ['localhost','127.0.0.1','0.0.0.0','::1','[::1]'].indexOf(h)>=0;}
  function apiBase(){var f=texto(window.TITULOS_API_BASE||'');if(f)return f.replace(/\/$/,'');if(esLocal())return 'http://127.0.0.1:8787';return 'https://titulos.pages.dev';}
  function proxyUrl(){return apiBase()+'/api/sheets';}
  function mensajeError(v){if(v&&v.message)return v.message;if(typeof v==='string')return v;return 'Error de Google Sheets.';}
  function solicitar(accion,payload,metodo){return fetch(proxyUrl(),{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({accion:accion,metodo:metodo||'POST',datos:payload||{}})}).then(function(resp){return resp.text().then(function(body){var json={};try{json=body?JSON.parse(body):{};}catch(e){throw new Error('El servicio de Google Sheets respondió en un formato no válido.');}if(!resp.ok||json.ok===false)throw new Error(json.mensaje||json.message||json.error||('Error HTTP '+resp.status));return json;});});}
  function leerConfiguracion(){return solicitar('CONFIGURACION_PUBLICA',{},'GET').then(function(r){return{endpoint:r.endpoint||'',url:r.endpoint||'',activo:r.activo!==false,timeoutMs:Number(r.timeoutMs||45000),nombre:r.nombre||'Google Sheets Titulación',actualizadoEn:'',origen:'firebase-url-cloudflare-token'};});}
  function guardarConfiguracion(data){data=data||{};var endpoint=texto(data.endpoint||data.url||data.webAppUrl);if(!endpoint)return Promise.reject(new Error('Ingresa la URL publicada de Apps Script.'));if(!window.ADFirebaseService||typeof window.ADFirebaseService.guardarDocumento!=='function')return Promise.reject(new Error('Firebase no está disponible para guardar la URL pública.'));return window.ADFirebaseService.guardarDocumento('app_config','titulos_sheets',{endpoint:endpoint,url:endpoint,activo:data.activo!==false,timeoutMs:Math.max(5000,numero(data.timeoutMs,45000)),nombre:texto(data.nombre||'Google Sheets Titulación'),actualizadoEn:new Date().toISOString()},{merge:true}).then(function(){return leerConfiguracion();});}
  function enviarGet(accion,payload){return solicitar(accion,payload,'GET').then(function(data){return{ok:true,status:200,data:data,configuracion:{origen:'cloudflare'}};});}
  function enviarPost(accion,payload){return solicitar(accion,payload,'POST').then(function(data){return{ok:true,status:200,data:data,configuracion:{origen:'cloudflare'}};});}
  function enviarAccion(accion,payload){var lecturas=['PING','LISTAR_COORDINADORES','LISTAR_PERIODOS_TITULACION','LISTAR_ENVIOS_COORDINADOR','LISTAR_ENVIOS_POR_CARRERA','VERIFICAR_ENVIO','CONSULTAR_ENVIO_CEDULA','RESUMEN_ADMINISTRADOR','LISTAR_BASE_ESTUDIANTES','LISTAR_PENDIENTES_SYNC','LISTAR_HISTORIAL_REPARACIONES','LISTAR_LOGS','ANALIZAR_GOOGLE_SHEETS','CONSULTAR_ESTUDIANTE'];return lecturas.indexOf(String(accion||'').toUpperCase())>=0?enviarGet(accion,payload):enviarPost(accion,payload);}
  function extraerLista(respuesta){var d=respuesta&&respuesta.data!==undefined?respuesta.data:respuesta;if(Array.isArray(d))return d;if(!d||typeof d!=='object')return[];var c=[d.envios,d.coordinadores,d.estudiantes,d.periodos,d.registros,d.pendientes,d.casos,d.historial,d.logs,d.resultado,d.result,d.data,d.data&&d.data.envios,d.data&&d.data.coordinadores,d.data&&d.data.estudiantes,d.data&&d.data.periodos];for(var i=0;i<c.length;i+=1)if(Array.isArray(c[i]))return c[i];return[];}
  function probarPing(){return enviarGet('PING',{});}
  function probarCoordinadores(){return enviarGet('LISTAR_COORDINADORES',{});}
  function probarEnvios(){return enviarGet('LISTAR_ENVIOS_POR_CARRERA',{carreras:'',carrera:'',estado:''});}
  function consultarCedula(cedula,periodo){cedula=texto(cedula).replace(/\D/g,'');if(!cedula)return Promise.reject(new Error('Ingresa una cédula.'));return enviarGet('VERIFICAR_ENVIO',{cedula:cedula,numeroIdentificacion:cedula,periodo:texto(periodo)});}
  window.ADSheetsService={STORAGE_KEY:'sin-localstorage',leerConfiguracion:leerConfiguracion,guardarConfiguracion:guardarConfiguracion,importarDesdeFirebase:leerConfiguracion,enviarAccion:enviarAccion,enviarGet:enviarGet,enviarPost:enviarPost,probarPing:probarPing,probarCoordinadores:probarCoordinadores,probarEnvios:probarEnvios,consultarCedula:consultarCedula,analizarGoogleSheets:function(p){return enviarGet('ANALIZAR_GOOGLE_SHEETS',p||{});},corregirGoogleSheets:function(p){return enviarPost('CORREGIR_GOOGLE_SHEETS',p||{});},listarHistorialReparaciones:function(l){return enviarGet('LISTAR_HISTORIAL_REPARACIONES',{limite:Math.max(1,numero(l,100))});},extraerLista:extraerLista,normalizar:function(d){return d||{};},mensajeError:mensajeError,proxyUrl:proxyUrl};
})(window);
