/* Gestión de servicios del Administrador v3. */
(function(window,document){
  'use strict';
  function api(){return window.ADAPIService;}function n(){return window.ADNormalizadores;}function ui(){return window.ADUI;}function state(){return window.ADState;}function $(id){return document.getElementById(id);}
  function servicioPorId(id){return(state().get().servicios||[]).find(function(item){return n().texto(item.clave||item.key).toUpperCase()===n().texto(id).toUpperCase();})||null;}
  function llenar(servicio){servicio=servicio||{};$('ad-servicio-clave').value=n().texto(servicio.clave||servicio.key||'TITULOS').toUpperCase();$('ad-servicio-nombre').value=n().texto(servicio.nombre||'');$('ad-servicio-endpoint').value=n().texto(servicio.endpoint||'');$('ad-servicio-secreto').value='';$('ad-servicio-spreadsheet').value=n().texto(servicio.spreadsheetId||'');$('ad-servicio-timeout').value=Number(servicio.timeoutMs||45000);$('ad-servicio-version').value=n().texto(servicio.version||'');$('ad-servicio-mensaje').value=n().texto(servicio.mensaje||'');$('ad-servicio-activo').checked=servicio.activo===true;state().setServicioEdicion(servicio);}
  function leerFormulario(){return{clave:n().texto($('ad-servicio-clave').value).toUpperCase(),nombre:n().texto($('ad-servicio-nombre').value),endpoint:n().texto($('ad-servicio-endpoint').value),secreto:n().texto($('ad-servicio-secreto').value),spreadsheetId:n().texto($('ad-servicio-spreadsheet').value),timeoutMs:Number($('ad-servicio-timeout').value||45000),version:n().texto($('ad-servicio-version').value),mensaje:n().texto($('ad-servicio-mensaje').value),activo:$('ad-servicio-activo').checked,estado:$('ad-servicio-activo').checked?'ACTIVO':'INACTIVO'};}
  function cargar(forzar){return api().listarServicios(forzar===true).then(function(respuesta){var lista=api().extraerServicios(respuesta);state().setLista('servicios',lista,'servicios');ui().renderServicios();return lista;});}
  function guardar(evento){evento.preventDefault();var form=evento.currentTarget,restaurar=ui().bloquear(form,true),datos=leerFormulario();if(!datos.clave||!datos.nombre){ui().estado('ad-estado-servicio','La clave y el nombre son obligatorios.','danger');restaurar();return;}ui().estado('ad-estado-servicio','Guardando servicio...','info');api().guardarServicio(datos).then(function(){ui().estado('ad-estado-servicio','Servicio guardado correctamente.','success');$('ad-servicio-secreto').value='';return cargar(true);}).catch(function(error){ui().estado('ad-estado-servicio',error.message||String(error),'danger');}).finally(restaurar);}
  function editar(id){var servicio=servicioPorId(id);if(servicio)llenar(servicio);}
  function toggle(id,activo){var servicio=servicioPorId(id);if(!servicio)return Promise.resolve();var datos={clave:n().texto(servicio.clave||servicio.key).toUpperCase(),nombre:servicio.nombre,endpoint:servicio.endpoint,spreadsheetId:servicio.spreadsheetId,timeoutMs:servicio.timeoutMs,version:servicio.version,mensaje:servicio.mensaje,activo:activo===true,estado:activo===true?'ACTIVO':'INACTIVO'};ui().estado('ad-estado-servicio','Actualizando servicio...','info');return api().guardarServicio(datos).then(function(){ui().estado('ad-estado-servicio','Estado actualizado.','success');return cargar(true);}).catch(function(error){ui().estado('ad-estado-servicio',error.message||String(error),'danger');});}
  function iniciar(){var form=$('ad-form-servicio');if(form)form.addEventListener('submit',guardar);}
  window.ADServicios=Object.freeze({iniciar:iniciar,cargar:cargar,editar:editar,toggle:toggle,llenar:llenar});
})(window,document);
