/* Feedback anónimo de IA. La persistencia real vive detrás de Firebase; nunca se conecta Neon desde el navegador. */
(function(window,document){'use strict';var generaciones=Object.create(null),enviados=Object.create(null);
  function texto(v,m){var s=String(v==null?'':v).replace(/\s+/g,' ').trim();s=s.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig,'[correo]').replace(/\b\d{7,15}\b/g,'[identificador]');return s.slice(0,Number(m||500));}
  function apiUrl(){var b=texto(window.TITULOS_API_BASE||'',400).replace(/\/$/,'');return b?b+'/api/aprendizaje':'';}
  function idEvento(){if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID();return'ia-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,12);}
  function enviar(payload){var url=apiUrl(),c=typeof AbortController==='function'?new AbortController():null,t;if(!url)return Promise.resolve({ok:false,omitido:true});if(c)t=window.setTimeout(function(){c.abort();},3500);return fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Titulos-App':'estudiantes'},signal:c?c.signal:undefined,body:JSON.stringify(payload)}).then(function(r){return r.ok?r.json().catch(function(){return{ok:true};}):{ok:false};}).catch(function(){return{ok:false};}).finally(function(){if(t)window.clearTimeout(t);});}
  function registrarGeneracion(d){d=d||{};var n=Number(d.numeroPropuesta||0),e=d.estudiante||{},o=Array.isArray(d.opciones)?d.opciones:[],id=idEvento();generaciones[n]=id;return enviar({action:'generation',eventId:id,numeroPropuesta:n,carrera:texto(e.nombreCarrera||e.carrera||e.NombreCarrera,160),opciones:o.slice(0,3).map(function(i,x){return{numero:Number(i.numero||x+1),titulo:texto(i.titulo,600),etapa:texto(i.etapa||i.codigoEtapa,60),puntaje:Number(i.puntaje||0)};})});}
  function registrarSeleccion(d){d=d||{};var n=Number(d.numeroPropuesta||0),t=texto(d.titulo,600),k=String(generaciones[n]||'')+'|'+n+'|'+t;if(!t||enviados[k])return Promise.resolve({ok:true,duplicado:true});enviados[k]=true;return enviar({action:'selection',eventId:generaciones[n]||'',numeroPropuesta:n,titulo:t,numeroSugerencia:Number(d.numeroSugerencia||0)});}
  document.addEventListener('ia-titulacion:sugerencia-seleccionada',function(e){registrarSeleccion(e&&e.detail||{});});
  window.EstudianteMVPIAAprendizaje=Object.freeze({registrarGeneracion:registrarGeneracion,registrarSeleccion:registrarSeleccion,version:'1.0.0'});
})(window,document);
