/* Google Sheets como única fuente del proceso operativo del estudiante. */
(function(window){
  'use strict';
  function cfg(){return window.EstudianteMVPConfig||null;}
  function utils(){return window.EstudianteMVPUtils||null;}
  function texto(v){return String(v===null||v===undefined?'':v).replace(/\s+/g,' ').trim();}
  function cedula(v){var u=utils();return u&&u.limpiarCedula?u.limpiarCedula(v):String(v||'').replace(/\D/g,'');}
  function esLocal(){var h=texto(window.location&&window.location.hostname).toLowerCase();return ['localhost','127.0.0.1','0.0.0.0','::1','[::1]'].indexOf(h)>=0;}
  function esArchivo(){return texto(window.location&&window.location.protocol).toLowerCase()==='file:';}
  function apiBase(){
    var f=texto(window.TITULOS_API_BASE||'');
    var origen;
    if(f)return f.replace(/\/$/,'');
    if(esLocal())return 'http://127.0.0.1:8787';
    if(esArchivo())return 'https://titulos.pages.dev';
    origen=texto(window.location&&window.location.origin);
    return origen&&origen!=='null'?origen.replace(/\/$/,''):'https://titulos.pages.dev';
  }
  function proxyUrl(){return apiBase()+'/api/sheets';}
  function enviarProxy(accion,datos,metodo){return fetch(proxyUrl(),{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-Titulos-App':'estudiantes'},body:JSON.stringify({accion:accion,metodo:metodo||'POST',datos:datos||{}})}).then(function(resp){return resp.text().then(function(body){var json={};try{json=body?JSON.parse(body):{};}catch(e){throw new Error('El servicio de registro respondió en un formato no válido.');}if(!resp.ok||json.ok===false)throw new Error(json.mensaje||json.message||json.error||('Error HTTP '+resp.status));return json;});});}
  function leerConfiguracion(){return enviarProxy('CONFIGURACION_PUBLICA',{},'GET').then(function(r){return{activo:r.activo!==false,endpoint:r.endpoint||'',nombre:r.nombre||'Google Sheets Titulación',timeoutMs:Number(r.timeoutMs||45000),raw:r};});}
  function guardarConfiguracion(){return Promise.reject(new Error('La configuración se administra de forma central.'));}
  function estadoEnvio(envio){return texto(envio&&(envio.estado||envio.estadoFinal||envio.estadoProceso||envio.estadoGoogleSheets)).toUpperCase();}
  function extraerEnvio(r){return r&&(r.envio||r.registro||r.data&&(r.data.envio||r.data.registro))||null;}
  function consultarEnvioPorCedula(valor){var c=cedula(valor);if(!c)return Promise.resolve({ok:false,encontrado:false,mensaje:'No se recibió una cédula válida.'});return enviarProxy('CONSULTAR_ENVIO_CEDULA',{cedula:c,numeroIdentificacion:c},'GET').then(function(r){var envio=extraerEnvio(r);var encontrado=r.encontrado===true||r.existe===true||Boolean(envio);var estado=estadoEnvio(envio);var permite=estado==='DEVUELTO'&&(envio&&envio.permitirReenvio!==false);return{ok:true,encontrado:encontrado&&!permite,permiteReenvio:permite,cedula:c,envio:envio,mensaje:r.mensaje||''};}).catch(function(error){return{ok:false,encontrado:false,cedula:c,error:error,mensaje:error.message||'No se pudo consultar el envío previo.'};});}
  function tituloTexto(item){if(typeof item==='string')return texto(item);item=item||{};return texto(item.tituloFinal||item.titulo||item.tituloMejorado||item.texto||item.title||'');}
  function normalizarPropuestas(payload){var lista=payload&&(payload.titulosEnviados||payload.propuestas)||[];return(Array.isArray(lista)?lista:[]).map(function(item,i){var obj=typeof item==='string'?{tituloFinal:item}:Object.assign({},item||{});obj.numero=Number(obj.numero||i+1);obj.tituloFinal=tituloTexto(obj);return obj;});}
  function construirPayloadSheets(payload){payload=payload||{};var est=payload.estudiante||{};var propuestas=normalizarPropuestas(payload);var periodoId=texto(payload.periodoId||est.periodoId||(cfg()&&cfg().obtener?cfg().obtener('proceso.periodoIdFallback',''):''));var periodoLabel=texto(payload.periodoLabel||est.periodoLabel||payload.periodo||periodoId);var c=cedula(payload.cedula||payload.numeroIdentificacion||est.cedula||est.numeroIdentificacion);var nombres=texto(payload.nombres||est.nombres||est.nombreCompleto);var carrera=texto(payload.carrera||payload.nombreCarrera||est.carrera||est.nombreCarrera);var codigo=texto(payload.codigoCarrera||est.codigoCarrera||est.CodigoCarrera);var fav=Number(payload.tituloPreferidoNumero||1);var favObj=propuestas.find(function(p){return Number(p.numero)===fav;})||propuestas[0]||{};var fecha=utils()&&utils().fechaIso?utils().fechaIso():new Date().toISOString();var id=(periodoId||'sin_periodo')+'__'+(c||'sin_cedula');var datos={fechaEnvio:fecha,fechaCliente:fecha,idRegistro:id,tituloId:id,codigoRegistro:id,cedula:c,numeroIdentificacion:c,nombres:nombres,estudiante:nombres,carrera:carrera,nombreCarrera:carrera,codigoCarrera:codigo,sede:texto(payload.sede||est.sede||est.Sede),modalidad:texto(payload.modalidad||est.modalidad||est.Modalidad),periodo:periodoLabel||periodoId,periodoId:periodoId,periodoLabel:periodoLabel,telegram:texto(payload.telegram||payload.telegramUser),telegramUser:texto(payload.telegram||payload.telegramUser),titulo1:tituloTexto(propuestas[0]),titulo2:tituloTexto(propuestas[1]),titulo3:tituloTexto(propuestas[2]),preferido:fav,tituloPreferidoNumero:fav,tituloPreferido:tituloTexto(favObj),tituloPreferidoTexto:tituloTexto(favObj),propuestas:propuestas,titulosEnviados:propuestas,estado:'PENDIENTE_REVISION',estadoFinal:'PENDIENTE_REVISION',estadoProceso:'PENDIENTE_REVISION',permitirReenvio:false,origenCaptura:'estudiantes-mvp',creadoEnLocal:payload.creadoEnLocal||'',enviadoEnLocal:payload.enviadoEnLocal||fecha};return Object.assign({accion:'ENVIO_ESTUDIANTE',tipo:'ENVIO',datos:datos},datos);}
  function enviarEnvio(payload){var construido=construirPayloadSheets(payload);return enviarProxy('ENVIO_ESTUDIANTE',construido,'POST').then(function(r){return{ok:true,idRegistro:r.idRegistro||r.tituloId||construido.idRegistro,mensaje:r.mensaje||'Envío guardado correctamente.',respuesta:r,raw:r};});}
  function probarConexion(){return enviarProxy('PING',{},'GET').then(function(r){return{ok:true,respuesta:r,mensaje:r.mensaje||'Conexión correcta.'};});}
  window.EstudianteMVPSheets=Object.freeze({leerConfiguracion:leerConfiguracion,guardarConfiguracion:guardarConfiguracion,consultarEnvioPorCedula:consultarEnvioPorCedula,enviarEnvio:enviarEnvio,probarConexion:probarConexion,construirPayloadSheets:construirPayloadSheets,proxyUrl:proxyUrl});
})(window);
