/* RESPALDO TITULOS APP como única base operativa del estudiante. */
(function(window){
'use strict';
function cfg(){return window.EstudianteMVPConfig||null;}function utils(){return window.EstudianteMVPUtils||null;}function texto(v){return String(v===null||v===undefined?'':v).replace(/\s+/g,' ').trim();}function cedula(v){var u=utils();return u&&u.limpiarCedula?u.limpiarCedula(v):String(v||'').replace(/\D/g,'');}
function esLocal(){var h=texto(window.location&&window.location.hostname).toLowerCase();return['localhost','127.0.0.1','0.0.0.0','::1','[::1]'].indexOf(h)>=0;}function esArchivo(){return texto(window.location&&window.location.protocol).toLowerCase()==='file:';}function apiBase(){var f=texto(window.TITULOS_API_BASE||''),o;if(f)return f.replace(/\/$/,'');if(esLocal())return'http://127.0.0.1:8788';if(esArchivo())return'https://titulos.pages.dev';o=texto(window.location&&window.location.origin);return o&&o!=='null'?o.replace(/\/$/,''):'https://titulos.pages.dev';}function proxyUrl(){return apiBase()+'/api/titulos';}
function enviarProxy(a,d,m){return fetch(proxyUrl(),{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-Titulos-App':'estudiantes'},body:JSON.stringify({accion:a,metodo:m||'POST',datos:d||{}})}).then(function(resp){return resp.text().then(function(body){var j={};try{j=body?JSON.parse(body):{};}catch(e){throw new Error('El servicio de Títulos respondió en un formato no válido.');}if(!resp.ok||j.ok===false)throw new Error(j.mensaje||j.message||j.error||('Error HTTP '+resp.status));return j;});});}
function leerConfiguracion(){return enviarProxy('CONFIGURACION_PUBLICA',{},'GET').then(function(r){return{activo:r.activo!==false,nombre:r.nombre||'RESPALDO TITULOS APP',timeoutMs:Number(r.timeoutMs||45000),version:r.version||'',estado:r.estado||'',origen:'claves',raw:r};});}function guardarConfiguracion(){return Promise.reject(new Error('La configuración se administra en la hoja Claves.'));}
function estadoEnvio(e){return texto(e&&(e.estado||e.estadoFinal||e.estadoProceso||e.estadoGoogleSheets)).toUpperCase();}function extraerEnvio(r){return r&&(r.envio||r.registro||r.data&&(r.data.envio||r.data.registro))||null;}
function consultarEnvioPorCedula(v){var id=cedula(v);if(!id)return Promise.resolve({ok:false,encontrado:false,mensaje:'No se recibió una cédula válida.'});return enviarProxy('CONSULTAR_ENVIO_CEDULA',{cedula:id,numeroIdentificacion:id},'GET').then(function(r){var e=extraerEnvio(r),encontrado=r.encontrado===true||r.existe===true||Boolean(e),st=estadoEnvio(e),permite=st==='DEVUELTO'&&(!e||e.permitirReenvio!==false);return{ok:true,encontrado:encontrado&&!permite,permiteReenvio:permite,cedula:id,envio:e,mensaje:r.mensaje||''};}).catch(function(error){return{ok:false,encontrado:false,cedula:id,error:error,mensaje:error.message||'No se pudo consultar el envío previo.'};});}
function tituloTexto(i){if(typeof i==='string')return texto(i);i=i||{};return texto(i.tituloFinal||i.titulo||i.tituloMejorado||i.texto||i.title||'');}
function normalizarPropuestas(p){var l=p&&(p.titulosEnviados||p.propuestas)||[];return(Array.isArray(l)?l:[]).map(function(i,n){var o=typeof i==='string'?{tituloFinal:i}:Object.assign({},i||{});o.numero=Number(o.numero||n+1);o.tituloFinal=tituloTexto(o);return o;});}
function construirPayloadSheets(payload){payload=payload||{};var e=payload.estudiante||{},ps=normalizarPropuestas(payload),pid=texto(payload.periodoId||e.periodoId||(cfg()&&cfg().obtener?cfg().obtener('proceso.periodoIdFallback',''):'')),pl=texto(payload.periodoLabel||e.periodoLabel||payload.periodo||pid),id=cedula(payload.cedula||payload.numeroIdentificacion||e.cedula||e.numeroIdentificacion),n=texto(payload.nombres||e.nombres||e.nombreCompleto),c=texto(payload.carrera||payload.nombreCarrera||e.carrera||e.nombreCarrera),cod=texto(payload.codigoCarrera||e.codigoCarrera||e.CodigoCarrera),favN=Number(payload.tituloPreferidoNumero||1),fav=ps.find(function(x){return Number(x.numero)===favN;})||ps[0]||{},fecha=utils()&&utils().fechaIso?utils().fechaIso():new Date().toISOString(),registro=(pid||'sin_periodo')+'__'+(id||'sin_cedula'),d={fechaEnvio:fecha,fechaCliente:fecha,idRegistro:registro,tituloId:registro,codigoRegistro:registro,cedula:id,numeroIdentificacion:id,nombres:n,estudiante:n,carrera:c,nombreCarrera:c,codigoCarrera:cod,sede:texto(payload.sede||e.sede||e.Sede),modalidad:texto(payload.modalidad||e.modalidad||e.Modalidad),periodo:pl||pid,periodoId:pid,periodoLabel:pl,telegram:texto(payload.telegram||payload.telegramUser),telegramUser:texto(payload.telegram||payload.telegramUser),titulo1:tituloTexto(ps[0]),titulo2:tituloTexto(ps[1]),titulo3:tituloTexto(ps[2]),preferido:favN,tituloPreferidoNumero:favN,tituloPreferido:tituloTexto(fav),tituloPreferidoTexto:tituloTexto(fav),propuestas:ps,titulosEnviados:ps,estado:'PENDIENTE_REVISION',estadoFinal:'PENDIENTE_REVISION',estadoProceso:'PENDIENTE_REVISION',permitirReenvio:false,origenCaptura:'estudiantes-mvp',creadoEnLocal:payload.creadoEnLocal||'',enviadoEnLocal:payload.enviadoEnLocal||fecha};return Object.assign({accion:'ENVIO_ESTUDIANTE',tipo:'ENVIO',datos:d},d);}
function enviarEnvio(payload){var p=construirPayloadSheets(payload);return enviarProxy('ENVIO_ESTUDIANTE',p,'POST').then(function(r){return{ok:true,estado:'PENDIENTE_REVISION',idRegistro:r.idRegistro||r.tituloId||p.idRegistro,mensaje:r.mensaje||'Envío guardado correctamente.',respuesta:r,raw:r};});}
function probarConexion(){return enviarProxy('PING',{},'GET').then(function(r){return{ok:true,respuesta:r,mensaje:r.mensaje||'Conexión correcta.'};});}
window.EstudianteMVPSheets=Object.freeze({leerConfiguracion:leerConfiguracion,guardarConfiguracion:guardarConfiguracion,consultarEnvioPorCedula:consultarEnvioPorCedula,enviarEnvio:enviarEnvio,probarConexion:probarConexion,construirPayloadSheets:construirPayloadSheets,proxyUrl:proxyUrl});
})(window);
