/* Coordinadores: períodos desde Requisitos y operaciones desde Títulos. */
(function(window,document){
'use strict';
var iniciado=false;var fuenteActual='google-sheets';
function state(){return window.CoordinadorMVPState||null;}function ui(){return window.CoordinadorMVPUI||null;}function modal(){return window.CoordinadorMVPModal||null;}function sheetsService(){return window.CoordinadorMVPSheetsPrimary||null;}function $(id){return document.getElementById(id);}function texto(v){return String(v===null||v===undefined?'':v).trim();}function textoError(e){if(!e)return'Error desconocido.';if(typeof e==='string')return e;if(e.message)return textoError(e.message);if(e.mensaje)return textoError(e.mensaje);if(e.error)return textoError(e.error);try{return JSON.stringify(e);}catch(x){return String(e);}}
function validarDependencias(){var f=[];if(!state())f.push('CoordinadorMVPState');if(!ui())f.push('CoordinadorMVPUI');if(!modal())f.push('CoordinadorMVPModal');if(!sheetsService())f.push('CoordinadorMVPSheetsPrimary');if(f.length)throw new Error('Faltan módulos: '+f.join(', '));}
function mostrarFuente(m,t){if(ui()&&typeof ui().mostrarEstado==='function')ui().mostrarEstado('estadoPrincipal',m,t||'info');}
function cargarCatalogos(){state().limpiarError();state().setCargando(true);mostrarFuente('Cargando períodos desde Requisitos y coordinadores desde Títulos...','info');return sheetsService().leerConfiguracion(true).then(function(cfg){if(!cfg||cfg.activo===false)throw new Error('Uno de los servicios configurados en Claves está inactivo.');return Promise.all([sheetsService().listarPeriodos(),sheetsService().listarCoordinadores()]);}).then(function(partes){var periodo=partes[0]||{},coordinadores=Array.isArray(partes[1])?partes[1]:[];if(!Array.isArray(periodo.periodos)||!periodo.periodos.length)throw new Error('REQUISITOS_BDLOCAL_SYNC no devolvió períodos activos.');state().setPeriodos(periodo.periodos,periodo.principal||periodo.periodos[0]);state().setCoordinadores(coordinadores);state().setEnvios([]);fuenteActual='google-sheets';state().limpiarError();mostrarFuente('Servicios conectados. Selecciona un coordinador para ver sus estudiantes.','success');return{ok:true,periodos:periodo.periodos,principal:periodo.principal,coordinadores:coordinadores};}).catch(function(error){var m=textoError(error);state().setPeriodos([],null);state().setCoordinadores([]);state().setEnvios([]);state().setError(new Error(m));mostrarFuente(m,'error');return{ok:false,error:m};}).finally(function(){state().setCargando(false);});}
function cargarTitulos(){var periodo=state().obtenerPeriodoActual(),coordinador=state().obtenerCoordinadorActual();if(!periodo){state().setEnvios([]);return Promise.resolve([]);}if(!coordinador){state().setEnvios([]);mostrarFuente('Selecciona un coordinador para filtrar sus carreras.','info');return Promise.resolve([]);}state().limpiarError();state().setCargando(true);return sheetsService().listarEnvios({periodo:periodo,coordinador:coordinador,carreras:coordinador.carreras||[],vista:state().obtenerVistaActual()}).then(function(lista){fuenteActual='google-sheets';state().setEnvios(lista||[]);var d=state().obtenerDiagnosticoFiltros?state().obtenerDiagnosticoFiltros():{};mostrarFuente(d.mostrados?'Se encontraron '+d.mostrados+' estudiante(s) para este coordinador.':'No hay coincidencias para los filtros seleccionados.',d.mostrados?'success':'warning');return lista||[];}).catch(function(error){var m=textoError(error);state().setEnvios([]);state().setError(new Error(m));mostrarFuente('No se pudieron cargar los envíos: '+m,'error');return[];}).finally(function(){state().setCargando(false);});}
function cambiarPeriodo(v){state().setPeriodoActual(v);return cargarTitulos();}function cambiarCoordinador(v){state().setCoordinadorActual(v);return cargarTitulos();}
function abrirDetalle(id){var envio=state().seleccionarEstudiante(id);if(!envio){ui().mostrarEstado('estadoPrincipal','No se encontró el estudiante.','error');return;}state().setCargando(true);var periodo=envio.periodoLabel||envio.periodo||envio.periodoId||'';sheetsService().consultarEnvioPorCedula(envio.cedula,periodo).then(function(actual){var combinado=Object.assign({},envio,actual,{id:envio.id||actual.id,_clave:envio._clave||actual._clave,fila:actual.fila||envio.fila,fuente:'RESPALDO TITULOS APP'});state().actualizarEnvioLocal(envio.id||envio.cedula,combinado);state().setEstudianteSeleccionado(combinado);modal().abrir(combinado);}).catch(function(error){ui().mostrarEstado('estadoPrincipal','No se abrió el detalle: '+textoError(error),'error');}).finally(function(){state().setCargando(false);});}
function aprobar(){var r=modal().obtenerResolucionAprobar();if(!r.ok)return;state().setCargando(true);sheetsService().aprobarEnvio(r.data.envio,r.data).then(function(x){modal().cerrar();ui().mostrarEstado('estadoPrincipal',x.mensaje||'Título aprobado en Google Sheets.','success');return cargarTitulos();}).catch(function(error){modal().mostrarEstado('No se guardó la aprobación: '+textoError(error),'error');}).finally(function(){state().setCargando(false);});}
function devolver(){var r=modal().obtenerResolucionDevolver();if(!r.ok)return;if(!window.confirm('¿Confirmas que deseas devolver estas propuestas al estudiante?'))return;state().setCargando(true);sheetsService().devolverEnvio(r.data.envio,r.data).then(function(x){modal().cerrar();ui().mostrarEstado('estadoPrincipal',x.mensaje||'Título devuelto en Google Sheets.','success');return cargarTitulos();}).catch(function(error){modal().mostrarEstado('No se realizó la devolución: '+textoError(error),'error');}).finally(function(){state().setCargando(false);});}
function mostrarDiagnostico(){ui().mostrarDiagnostico();ui().escribirDiagnostico({estado:'probando',fuentePrincipal:'Google Sheets',fecha:new Date().toISOString()});Promise.allSettled([sheetsService().leerConfiguracion(true),sheetsService().diagnostico(),sheetsService().listarCoordinadores(),sheetsService().listarPeriodos()]).then(function(p){ui().escribirDiagnostico({fuentePrincipal:'Google Sheets',fuenteActual:fuenteActual,configuracion:p[0].status==='fulfilled'?p[0].value:{error:textoError(p[0].reason)},diagnostico:p[1].status==='fulfilled'?p[1].value:{error:textoError(p[1].reason)},coordinadores:p[2].status==='fulfilled'?{ok:true,total:p[2].value.length}:{ok:false,error:textoError(p[2].reason)},periodos:p[3].status==='fulfilled'?p[3].value:{error:textoError(p[3].reason)},consultaEnvios:sheetsService().obtenerDiagnosticoConsulta?sheetsService().obtenerDiagnosticoConsulta():{},filtros:state().obtenerDiagnosticoFiltros?state().obtenerDiagnosticoFiltros():{},periodoActual:state().obtenerPeriodoActual(),coordinadorActual:state().obtenerCoordinadorActual(),firebase:{eliminado:true},fecha:new Date().toISOString()});});}
function conectarEventos(){var p=$('periodoSelect'),c=$('coordinadorSelect'),b=$('buscadorInput');if(p)p.addEventListener('change',function(){cambiarPeriodo(p.value);});if(c)c.addEventListener('change',function(){cambiarCoordinador(c.value);});if(b)b.addEventListener('input',function(){state().setBusqueda(b.value);});document.addEventListener('click',function(e){var x=e.target&&e.target.closest?e.target.closest('[data-accion]'):null;if(!x)return;var a=x.getAttribute('data-accion');if(a==='cambiar-vista'){state().setVistaActual(x.getAttribute('data-vista'));cargarTitulos();}else if(a==='actualizar-datos')cargarCatalogos();else if(a==='ver-detalle')abrirDetalle(x.getAttribute('data-envio-id'));else if(a==='cerrar-modal')modal().cerrar();else if(a==='aprobar-envio')aprobar();else if(a==='devolver-envio')devolver();else if(a==='mostrar-diagnostico')mostrarDiagnostico();else if(a==='ocultar-diagnostico')ui().ocultarDiagnostico();});document.addEventListener('keydown',function(e){if(e.key==='Escape')modal().cerrar();});}
function iniciar(){if(iniciado)return;iniciado=true;try{validarDependencias();state().iniciar();ui().iniciar();modal().iniciar();conectarEventos();cargarCatalogos();}catch(error){var e=$('estadoPrincipal');if(e){e.className='status-message is-error';e.textContent=textoError(error);}console.error('[CoordinadorMVPApp]',error);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciar);else iniciar();
window.CoordinadorMVPApp=Object.freeze({iniciar:iniciar,cargarCatalogos:cargarCatalogos,cargarTitulos:cargarTitulos,aprobar:aprobar,devolver:devolver,mostrarDiagnostico:mostrarDiagnostico,obtenerFuenteActual:function(){return fuenteActual;}});
})(window,document);
