/* Coordinadores: operación rápida desde RESPALDO TITULOS APP. */
(function(window,document){
'use strict';
var iniciado=false,fuenteActual='RESPALDO TITULOS APP';
function state(){return window.CoordinadorMVPState||null;}
function ui(){return window.CoordinadorMVPUI||null;}
function modal(){return window.CoordinadorMVPModal||null;}
function sheets(){return window.CoordinadorMVPSheetsPrimary||null;}
function $(id){return document.getElementById(id);}
function textoError(e){if(!e)return'Error desconocido.';if(typeof e==='string')return e;if(e.message)return textoError(e.message);if(e.mensaje)return textoError(e.mensaje);if(e.error)return textoError(e.error);try{return JSON.stringify(e);}catch(x){return String(e);}}
function validar(){var f=[];if(!state())f.push('CoordinadorMVPState');if(!ui())f.push('CoordinadorMVPUI');if(!modal())f.push('CoordinadorMVPModal');if(!sheets())f.push('CoordinadorMVPSheetsPrimary');if(f.length)throw new Error('Faltan módulos: '+f.join(', '));}
function estado(m,t){ui().mostrarEstado('estadoPrincipal',m,t||'info');}
function resumen(){var d=state().obtenerDiagnosticoFiltros?state().obtenerDiagnosticoFiltros():{};estado(d.mostrados?'Mostrando '+d.mostrados+' estudiante(s).':'No hay coincidencias para los filtros seleccionados.',d.mostrados?'success':'warning');}

function cargarCatalogos(forzar){
 state().limpiarError();state().setCargando(true);estado(forzar?'Actualizando RESPALDO TITULOS APP...':'Cargando períodos, coordinadores y envíos...','info');
 if(forzar&&sheets().invalidarCacheEnvios)sheets().invalidarCacheEnvios();
 if(forzar&&sheets().limpiarCache)sheets().limpiarCache();
 return Promise.all([sheets().listarPeriodos({forzar:forzar===true}),sheets().listarCoordinadores(forzar===true)])
 .then(function(p){var periodos=p[0]||{},coordinadores=Array.isArray(p[1])?p[1]:[];if(!periodos.periodos||!periodos.periodos.length)throw new Error('RESPALDO TITULOS APP no devolvió períodos disponibles.');state().setPeriodos(periodos.periodos,periodos.principal||periodos.periodos[0]);state().setCoordinadores(coordinadores);state().setEnvios(Array.isArray(periodos.envios)?periodos.envios:[]);fuenteActual='RESPALDO TITULOS APP';state().limpiarError();if(state().obtenerCoordinadorActual())resumen();else estado('Datos cargados. Selecciona un coordinador.','success');return{ok:true,periodos:periodos.periodos,coordinadores:coordinadores,envios:periodos.envios||[]};})
 .catch(function(e){var m=textoError(e);state().setPeriodos([],null);state().setCoordinadores([]);state().setEnvios([]);state().setError(new Error(m));estado(m,'error');return{ok:false,error:m};})
 .finally(function(){state().setCargando(false);});
}
function cargarTitulos(forzar){state().setCargando(true);return sheets().listarEnvios({forzar:forzar===true}).then(function(lista){state().setEnvios(lista||[]);resumen();return lista||[];}).catch(function(e){estado('No se pudieron actualizar los envíos: '+textoError(e),'error');return[];}).finally(function(){state().setCargando(false);});}
function abrirDetalle(id){var envio=state().seleccionarEstudiante(id);if(!envio){estado('No se encontró el estudiante.','error');return;}state().setEstudianteSeleccionado(envio);modal().abrir(envio);}
function aprobar(){var r=modal().obtenerResolucionAprobar();if(!r.ok)return;state().setCargando(true);sheets().aprobarEnvio(r.data.envio,r.data).then(function(x){modal().cerrar();estado(x.mensaje||'Título aprobado.','success');if(sheets().invalidarCacheEnvios)sheets().invalidarCacheEnvios();return cargarTitulos(true);}).catch(function(e){modal().mostrarEstado('No se guardó la aprobación: '+textoError(e),'error');}).finally(function(){state().setCargando(false);});}
function devolver(){var r=modal().obtenerResolucionDevolver();if(!r.ok)return;if(!window.confirm('¿Confirmas que deseas devolver estas propuestas al estudiante?'))return;state().setCargando(true);sheets().devolverEnvio(r.data.envio,r.data).then(function(x){modal().cerrar();estado(x.mensaje||'Título devuelto.','success');if(sheets().invalidarCacheEnvios)sheets().invalidarCacheEnvios();return cargarTitulos(true);}).catch(function(e){modal().mostrarEstado('No se realizó la devolución: '+textoError(e),'error');}).finally(function(){state().setCargando(false);});}
function diagnostico(){ui().mostrarDiagnostico();ui().escribirDiagnostico({estado:'probando',fuentePrincipal:fuenteActual});Promise.allSettled([sheets().leerConfiguracion(),sheets().diagnostico(),sheets().listarCoordinadores(),sheets().listarPeriodos()]).then(function(p){ui().escribirDiagnostico({fuentePrincipal:fuenteActual,configuracion:p[0].status==='fulfilled'?p[0].value:{error:textoError(p[0].reason)},conexion:p[1].status==='fulfilled'?p[1].value:{error:textoError(p[1].reason)},coordinadores:p[2].status==='fulfilled'?p[2].value.length:textoError(p[2].reason),periodos:p[3].status==='fulfilled'?p[3].value.periodos.length:textoError(p[3].reason),consultaEnvios:sheets().obtenerDiagnosticoConsulta?sheets().obtenerDiagnosticoConsulta():{},filtros:state().obtenerDiagnosticoFiltros(),fecha:new Date().toISOString()});});}
function eventos(){var p=$('periodoSelect'),c=$('coordinadorSelect'),b=$('buscadorInput');if(p)p.addEventListener('change',function(){state().setPeriodoActual(p.value);});if(c)c.addEventListener('change',function(){state().setCoordinadorActual(c.value);});if(b)b.addEventListener('input',function(){state().setBusqueda(b.value);});document.addEventListener('click',function(e){var x=e.target&&e.target.closest?e.target.closest('[data-accion]'):null;if(!x)return;var a=x.getAttribute('data-accion');if(a==='cambiar-vista')state().setVistaActual(x.getAttribute('data-vista'));else if(a==='actualizar-datos')cargarCatalogos(true);else if(a==='ver-detalle')abrirDetalle(x.getAttribute('data-envio-id'));else if(a==='cerrar-modal')modal().cerrar();else if(a==='aprobar-envio')aprobar();else if(a==='devolver-envio')devolver();else if(a==='mostrar-diagnostico')diagnostico();else if(a==='ocultar-diagnostico')ui().ocultarDiagnostico();});document.addEventListener('keydown',function(e){if(e.key==='Escape')modal().cerrar();});}
function iniciar(){if(iniciado)return;iniciado=true;try{validar();state().iniciar();ui().iniciar();modal().iniciar();eventos();cargarCatalogos(false);}catch(e){var el=$('estadoPrincipal');if(el){el.className='status-message is-error';el.textContent=textoError(e);}console.error('[CoordinadorMVPApp]',e);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciar);else iniciar();
window.CoordinadorMVPApp=Object.freeze({iniciar:iniciar,cargarCatalogos:cargarCatalogos,cargarTitulos:cargarTitulos,aprobar:aprobar,devolver:devolver,mostrarDiagnostico:diagnostico,obtenerFuenteActual:function(){return fuenteActual;}});
})(window,document);
