/* Coordinadores: Google Sheets exclusivo mediante Cloudflare. */
(function(window){
  'use strict';
  function config(){return window.CoordinadorMVPConfig||null;}
  function utils(){return window.CoordinadorMVPUtils||null;}
  function texto(v){return String(v===null||v===undefined?'':v).trim();}
  function apiBase(){return texto(window.TITULOS_API_BASE||'https://titulos.pages.dev').replace(/\/$/,'');}
  function mensajeError(v){if(v&&v.message)return v.message;if(typeof v==='string')return v;return'Error de Google Sheets.';}
  function solicitar(accion,payload,metodo){return fetch(apiBase()+'/api/sheets',{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({accion:accion,metodo:metodo||'POST',datos:payload||{}})}).then(function(resp){return resp.text().then(function(body){var j={};try{j=body?JSON.parse(body):{};}catch(e){throw new Error('El servicio respondió en un formato no válido.');}if(!resp.ok||j.ok===false)throw new Error(j.mensaje||j.error||('Error HTTP '+resp.status));return j;});});}
  function leerConfiguracion(){return solicitar('CONFIGURACION_PUBLICA',{},'GET').then(function(r){return{endpoint:r.endpoint||'',activo:r.activo!==false,timeoutMs:Number(r.timeoutMs||45000),nombre:r.nombre||'Google Sheets Titulación',origen:'cloudflare'};});}
  function enviarGet(a,p){return solicitar(a,p,'GET');}
  function enviarPost(a,p){return solicitar(a,p,'POST');}
  function enviarAccion(a,p){var lecturas=['PING','LISTAR_COORDINADORES','LISTAR_PERIODOS_TITULACION','LISTAR_ENVIOS_COORDINADOR','LISTAR_ENVIOS_POR_CARRERA','VERIFICAR_ENVIO','CONSULTAR_ENVIO_CEDULA'];return lecturas.indexOf(String(a||'').toUpperCase())>=0?enviarGet(a,p):enviarPost(a,p);}
  function extraerListaRecursiva(v,claves,n){if(n>6||v===null||v===undefined)return[];if(Array.isArray(v))return v;if(typeof v!=='object')return[];for(var i=0;i<claves.length;i+=1)if(Array.isArray(v[claves[i]]))return v[claves[i]];var ks=Object.keys(v);for(var j=0;j<ks.length;j+=1){var r=extraerListaRecursiva(v[ks[j]],claves,n+1);if(r.length)return r;}return[];}
  function extraerLista(r,tipo){var c=tipo==='coordinadores'?['coordinadores','registros','filas','rows','items','resultado','result','data']:tipo==='periodos'?['periodos','registros','items','resultado','result','data']:['envios','registros','filas','rows','items','resultado','result','data'];return extraerListaRecursiva(r,c,0);}
  function campo(f,a,fallback){return utils().obtenerCampoFlexible(f||{},a||[],fallback===undefined?'':fallback);}
  function normalComp(v){return texto(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
  function favorito(v,t){var x=texto(v);if(/^[123]$/.test(x))return Number(x);var m=x.match(/(?:t[ií]tulo|propuesta|opci[oó]n|favorito)\s*#?\s*([123])/i);if(m)return Number(m[1]);var n=normalComp(x);for(var i=0;i<3;i+=1)if(n&&normalComp(t[i])===n)return i+1;return 0;}
  function normalizarCoordinador(f,i){var col=config().data.columnas.coordinadores;var nombre=utils().limpiarTexto(campo(f,col.nombre,''));var carreras=utils().normalizarCarreras(campo(f,col.carreras,''));var activo=utils().parseBoolean(campo(f,col.activo,'ACTIVO'),true);return{id:utils().normalizarClave(f.id||f.idRegistro||nombre||('coordinador_'+i)),nombre:nombre,carreras:carreras,carrerasTexto:utils().carrerasComoTexto(carreras),activo:activo,fuente:'google-sheets',raw:f||{}};}
  function normalizarEnvio(f,i){var col=config().data.columnas.envios;f=f||{};var tit=[utils().limpiarTitulo(campo(f,col.titulo1,'')),utils().limpiarTitulo(campo(f,col.titulo2,'')),utils().limpiarTitulo(campo(f,col.titulo3,''))];var prefRaw=utils().limpiarTexto(campo(f,col.preferido,''));var pref=favorito(prefRaw,tit);var estado=utils().normalizarEstado(utils().limpiarTexto(campo(f,col.estado,''))||utils().limpiarTexto(campo(f,col.estadoFirebase,''))||config().obtenerEstado('pendiente'));if(estado==='ENVIADO'||estado==='PENDIENTE_SYNC')estado=config().obtenerEstado('pendiente');var periodo=utils().limpiarTexto(campo(f,col.periodo,''));var id=utils().limpiarTexto(campo(f,col.idRegistro,''))||utils().limpiarTexto(f.id||f.ID||f._id||'');var e={id:id,_clave:id,fila:f.__fila||f.fila||f.rowNumber||i+2,cedula:utils().limpiarCedula(campo(f,col.cedula,'')),nombres:utils().limpiarTexto(campo(f,col.nombres,'')),carrera:utils().limpiarTexto(campo(f,col.carrera,'')),codigoCarrera:utils().limpiarTexto(f.codigoCarrera||f.CodigoCarrera||''),periodo:periodo,periodoLabel:utils().limpiarTexto(f.periodoLabel||periodo),periodoId:utils().limpiarTexto(f.periodoId||periodo),telegram:utils().limpiarTexto(campo(f,col.telegram,'')),estado:estado,fechaEnvio:utils().limpiarTexto(campo(f,col.fechaEnvio,'')),titulo1:tit[0],titulo2:tit[1],titulo3:tit[2],tituloPreferido:prefRaw||String(pref||''),tituloPreferidoNumero:pref,tituloPreferidoTexto:pref?tit[pref-1]:prefRaw,preferido:pref||prefRaw,tituloAprobado:utils().limpiarTitulo(campo(f,col.tituloAprobado,'')),comentarioCoordinador:utils().limpiarTextoMultilinea(campo(f,col.comentarioCoordinador,'')),coordinador:utils().limpiarTexto(campo(f,col.coordinador,'')),fechaRevision:utils().limpiarTexto(campo(f,col.fechaRevision,'')),fuente:'google-sheets',raw:f};if(!e.id)e.id=e.cedula||('envio_'+i);return e;}
  function listarCoordinadores(){return enviarGet('LISTAR_COORDINADORES',{}).then(function(r){var l=extraerLista(r,'coordinadores').map(normalizarCoordinador).filter(function(x){return x&&x.activo!==false&&x.nombre;});if(!l.length)throw new Error('La hoja Coordinadores no devolvió registros activos.');return l;});}
  function listarPeriodos(){return enviarGet('LISTAR_PERIODOS_TITULACION',{}).then(function(r){var ps=extraerLista(r,'periodos').map(function(p){return{id:texto(p.id||p.periodoId),label:texto(p.label||p.periodoLabel||p.nombre||p.id),activo:p.activo!==false,principal:p.principal===true};}).filter(function(p){return p.id&&p.activo;});var principal=r.principal||r.data&&r.data.principal||ps.find(function(p){return p.principal;})||ps[0]||null;return{periodos:ps,principal:principal};});}
  function listarEnvios(op){op=op||{};var carreras=op.carreras||(op.coordinador&&op.coordinador.carreras)||[];return enviarGet('LISTAR_ENVIOS_POR_CARRERA',{carreras:Array.isArray(carreras)?carreras.join(','):carreras,carrera:Array.isArray(carreras)?carreras.join(','):carreras,estado:'',periodo:op.periodo||op.periodoId||''}).then(function(r){return extraerLista(r,'envios').map(normalizarEnvio).filter(function(x){return x&&x.cedula&&x.titulo1&&x.titulo2&&x.titulo3;});});}
  function consultarEnvioPorCedula(c,p){c=utils().limpiarCedula(c);if(!c)return Promise.reject(new Error('No se recibió una cédula válida.'));return enviarGet('VERIFICAR_ENVIO',{cedula:c,numeroIdentificacion:c,periodo:texto(p)}).then(function(r){var e=r.envio||r.registro||r.data&& (r.data.envio||r.data.registro);if(!e){var l=extraerLista(r,'envios');e=l[l.length-1];}if(!e)throw new Error('Google Sheets no devolvió el envío.');return normalizarEnvio(e,0);});}
  function nombreCoord(v){return typeof v==='string'?v:texto(v&& (v.nombre||v.coordinador||v.id));}
  function aprobarEnvio(e,res){e=e||{};res=res||{};var final=utils().limpiarTitulo(res.tituloFinal);var original=utils().limpiarTitulo(res.tituloOriginal);if(!final)return Promise.reject(new Error(config().obtener('textos.seleccionaTitulo')));var estado=final===original?config().obtenerEstado('aprobado'):config().obtenerEstado('reemplazado');var p={cedula:e.cedula,numeroIdentificacion:e.cedula,periodo:e.periodoLabel||e.periodo,estudiante:e.nombres,nombres:e.nombres,carrera:e.carrera,coordinador:nombreCoord(res.coordinador),estadoFinal:estado,estado:estado,tituloElegido:original||final,preferido:original||final,tituloCorregido:final!==original?final:'',observacion:utils().limpiarTextoMultilinea(res.comentarioCoordinador),comentario:utils().limpiarTextoMultilinea(res.comentarioCoordinador),fechaResolucion:utils().fechaIso(),permitirReenvio:false};return enviarPost('GUARDAR_RESOLUCION',p).then(function(r){return{ok:true,estado:estado,mensaje:r.mensaje||config().obtener('textos.aprobarOk'),respuesta:r,payload:p};});}
  function devolverEnvio(e,res){e=e||{};res=res||{};var comentario=utils().limpiarTextoMultilinea(res.comentarioCoordinador);if(comentario.length<4)return Promise.reject(new Error(config().obtener('textos.comentarioDevolucion')));var estado=config().obtenerEstado('devuelto');var elegido=e.tituloPreferidoTexto||e.tituloPreferido||e.titulo1||'';var p={cedula:e.cedula,numeroIdentificacion:e.cedula,periodo:e.periodoLabel||e.periodo,estudiante:e.nombres,nombres:e.nombres,carrera:e.carrera,coordinador:nombreCoord(res.coordinador),estadoFinal:estado,estado:estado,tituloElegido:elegido,preferido:elegido,tituloCorregido:'',observacion:comentario,comentario:comentario,fechaResolucion:utils().fechaIso(),permitirReenvio:true};return enviarPost('GUARDAR_RESOLUCION',p).then(function(r){return{ok:true,estado:estado,mensaje:r.mensaje||config().obtener('textos.devolverOk'),respuesta:r,payload:p};});}
  function diagnostico(){return Promise.all([leerConfiguracion(),enviarGet('PING',{})]).then(function(p){return{ok:true,fuentePrincipal:'Google Sheets',endpointConfigurado:Boolean(p[0].endpoint),activo:p[0].activo,respuesta:p[1],fecha:new Date().toISOString()};});}
  window.CoordinadorMVPSheetsPrimary=Object.freeze({leerConfiguracion:leerConfiguracion,enviarAccion:enviarAccion,enviarGet:enviarGet,enviarPost:enviarPost,listarCoordinadores:listarCoordinadores,listarPeriodos:listarPeriodos,listarEnvios:listarEnvios,consultarEnvioPorCedula:consultarEnvioPorCedula,aprobarEnvio:aprobarEnvio,devolverEnvio:devolverEnvio,diagnostico:diagnostico,normalizarCoordinador:normalizarCoordinador,normalizarEnvio:normalizarEnvio,mensajeError:mensajeError});
})(window);
