import { getPublicStatus, runService } from '../_lib/claves.js';
import { corsHeaders, jsonReply, normalizeAction, readJson, rejectUnknownOrigin, text } from '../_lib/http.js';

const ALLOWED=new Set(['CONFIGURACION_PUBLICA','PING','LISTAR_PERIODOS_TITULACION','LISTAR_PERIODOS_PUBLICOS','CONSULTAR_ESTUDIANTE','CONSULTAR_ESTUDIANTE_TITULACION','LISTAR_CARRERAS_PERIODO']);
const cedula=v=>{const d=text(v).replace(/\D/g,'');return d.length===9?'0'+d:d;};
function table(r,n){r=r&&r.respuesta||r&&r.data||r||{};const t=r.tables||r.result&&r.result.tables||r.data&&r.data.tables||{};return Array.isArray(t[n])?t[n]:Array.isArray(r[n])?r[n]:Array.isArray(r[n.toLowerCase()])?r[n.toLowerCase()]:[];}
function periods(r){r=r&&r.respuesta||r&&r.data||r||{};const list=r.periodos||r.periods||r.result&&(r.result.periodos||r.result.periods)||r.tables&&r.tables.Periodos||[];const map=new Map();(Array.isArray(list)?list:[]).forEach(x=>{x=x||{};const id=text(x.periodoId||x.periodoCanonicoId||x.id||x.value||x.key),label=text(x.periodoLabel||x.periodoCanonicoLabel||x.label||x.nombre||id);if(id&&!map.has(id)&&text(x.estado||'ACTIVO').toUpperCase()!=='INACTIVO')map.set(id,{id,periodoId:id,label:label||id,periodoLabel:label||id,activo:true,principal:x.principal===true});});const ps=[...map.values()];return{periodos:ps,principal:ps.find(x=>x.principal)||ps[0]||null};}
async function call(env,action,payload){return runService(env,'REQUISITOS',action,'POST',payload||{},'consulta');}
async function listPeriods(env){const p=periods(await call(env,'pull_bl2',{scope:'periods',includeData:false}));return{ok:true,tipo:'LISTAR_PERIODOS_TITULACION',...p,total:p.periodos.length,fuente:'REQUISITOS_BDLOCAL_SYNC'};}
function student(x,fallback){x=x||{};const id=cedula(x.cedula||x.numeroIdentificacion||x.NumeroIdentificacion||x.Cedula||x['Cédula']),p=text(x.periodoId||x.periodoCanonicoId||x.periodId||fallback),carrera=text(x.NombreCarrera||x.nombreCarrera||x.carrera||x.Carrera),nombres=text(x.Nombres||x.nombres||x.nombre||x.Nombre);return{id:text(x.id||x._id||x.studentId||id),cedula:id,numeroIdentificacion:id,Nombres:nombres,nombres,CodigoCarrera:text(x.CodigoCarrera||x.codigoCarrera),codigoCarrera:text(x.CodigoCarrera||x.codigoCarrera),NombreCarrera:carrera,nombreCarrera:carrera,carrera,Sede:text(x.Sede||x.sede),sede:text(x.Sede||x.sede),HorarioComplexivo:text(x.HorarioComplexivo||x.horarioComplexivo),horarioComplexivo:text(x.HorarioComplexivo||x.horarioComplexivo),estadoMatricula:text(x.estadoMatricula||x.EstadoMatricula||'ACTIVO'),division:text(x.division||x.Division),periodoId:p,periodoLabel:text(x.periodoLabel||x.periodoCanonicoLabel||x.PeriodoLabel||p),CorreoInstitucional:text(x.CorreoInstitucional||x.correoInstitucional),correoInstitucional:text(x.CorreoInstitucional||x.correoInstitucional),CorreoPersonal:text(x.CorreoPersonal||x.correoPersonal),correoPersonal:text(x.CorreoPersonal||x.correoPersonal),Celular:text(x.Celular||x.celular),celular:text(x.Celular||x.celular),Academico:text(x.Academico||x['Académico']),Documentacion:text(x.Documentacion||x['Documentación']),Financiero:text(x.Financiero),Ingles:text(x.Ingles||x['Inglés']),Titulacion:text(x.Titulacion||x['Titulación']),Vinculacion:text(x.Vinculacion||x['Vinculación']),PracticasVinculacion:text(x.PracticasVinculacion||x['PrácticasVinculacion']),SeguimientoGraduados:text(x.SeguimientoGraduados),ActualizacionDatos:text(x.ActualizacionDatos||x['ActualizaciónDatos']),AprobacionTitulacion:text(x.AprobacionTitulacion||x['AprobaciónTitulacion']),AprobacionComplexivoProyecto:text(x.AprobacionComplexivoProyecto||x['AprobaciónComplexivoProyecto'])};}
async function pull(env,p){return call(env,'pull_bl2',{scope:p?'period':'all',periodoId:p||'',includeData:true});}
async function consult(env,d){const c=cedula(d.cedula||d.numeroIdentificacion||d.identificacion);if(!c)throw new Error('No se recibió una cédula válida.');let p=text(d.periodoId||d.periodo||d.periodoLabel);if(!p){const ps=await listPeriods(env);p=ps.principal&&ps.principal.id||'';}const found=table(await pull(env,p),'Estudiantes').map(x=>student(x,p)).find(x=>x.cedula===c);if(!found)return{ok:true,encontrado:false,existe:false,cedula:c,periodoId:p,mensaje:'No encontramos un estudiante con esa cédula en REQUISITOS_BDLOCAL_SYNC.'};return{ok:true,encontrado:true,existe:true,estudiante:found,registro:found,periodoId:found.periodoId,periodoLabel:found.periodoLabel,fuente:'REQUISITOS_BDLOCAL_SYNC',mensaje:'Estudiante encontrado correctamente.'};}
function publicService(status,key){const list=Array.isArray(status.servicios)?status.servicios:[];return list.find(x=>String(x.clave||x.key||'').toUpperCase()===key)||null;}
export async function onRequest({request,env}){const bad=rejectUnknownOrigin(request);if(bad)return bad;if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(request)});if(request.method!=='POST')return jsonReply(request,{ok:false,mensaje:'Método no permitido.'},405);try{const input=await readJson(request),action=normalizeAction(input.accion||input.action||input.tipo),data=input.datos&&typeof input.datos==='object'?{...input,...input.datos}:{...input};if(!ALLOWED.has(action))return jsonReply(request,{ok:false,mensaje:'REQUISITOS_BDLOCAL_SYNC es de solo consulta.'},403);if(action==='CONFIGURACION_PUBLICA'){const item=publicService(await getPublicStatus(env),'REQUISITOS');if(!item)throw new Error('REQUISITOS no está configurado en Claves.');return jsonReply(request,{ok:true,activo:item.activo===true,nombre:item.nombre||'REQUISITOS_BDLOCAL_SYNC',version:item.version||'',estado:item.estado||'',mensaje:item.mensaje||'',soloLectura:true,origenConfig:'claves'});}if(action==='PING')return jsonReply(request,(await call(env,'ping',{})).respuesta||await call(env,'ping',{}));if(action==='LISTAR_PERIODOS_TITULACION'||action==='LISTAR_PERIODOS_PUBLICOS')return jsonReply(request,await listPeriods(env));if(action==='CONSULTAR_ESTUDIANTE'||action==='CONSULTAR_ESTUDIANTE_TITULACION')return jsonReply(request,await consult(env,data));if(action==='LISTAR_CARRERAS_PERIODO'){const p=text(data.periodoId||data.periodo||data.periodoLabel),c=table(await pull(env,p),'Carreras');return jsonReply(request,{ok:true,carreras:c,registros:c,total:c.length,periodoId:p,fuente:'REQUISITOS_BDLOCAL_SYNC'});}throw new Error('Acción no implementada.');}catch(error){return jsonReply(request,{ok:false,servicio:'REQUISITOS',mensaje:error.message||String(error)},502);}}
