(function(window,document){'use strict';
var state={sesion:'',investigador:null,carreras:[],carreraActual:'',pendientes:[],revision:null,heartbeat:null,modoAcceso:'consulta'};
function $(id){return document.getElementById(id)}
function text(v){return String(v==null?'':v).trim()}
function norm(v){return text(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function esc(v){return text(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function api(action,data){return fetch('/api/investigadores',{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-Titulos-App':'investigadores'},body:JSON.stringify({accion:action,datos:Object.assign({},data||{},state.sesion?{sesion:state.sesion}:{})})}).then(function(r){return r.json().then(function(j){if(!r.ok||j.ok===false)throw new Error(j.mensaje||'No se pudo completar la operación.');return j})})}
function status(id,msg,type){var el=$(id);if(!el)return;el.textContent=msg||'';el.className='status '+(type||'')}
function view(name){['login','dashboard','career','review'].forEach(function(v){var el=$(v+'View');if(el)el.hidden=v!==name})}
function guardarSesion(){try{sessionStorage.setItem('investigacion_sesion',state.sesion);sessionStorage.setItem('investigacion_nombre',state.investigador&&state.investigador.nombre||'')}catch(e){}}
function limpiarSesion(){state.sesion='';state.investigador=null;try{sessionStorage.removeItem('investigacion_sesion');sessionStorage.removeItem('investigacion_nombre')}catch(e){}}
function consultarAcceso(){var c=text($('cedulaInput').value).replace(/\D/g,'');if(c.length!==10){status('loginStatus','Ingresa una cédula válida.','error');return}status('loginStatus','Consultando acceso...','');api('CONSULTAR_ACCESO',{cedula:c}).then(function(r){if(!r.encontrado)throw new Error(r.mensaje||'No autorizado.');state.modoAcceso=r.requiereRegistroPin?'registro':'login';$('pinWrap').hidden=false;$('pinConfirmWrap').hidden=state.modoAcceso!=='registro';$('pinInput').setAttribute('autocomplete',state.modoAcceso==='registro'?'new-password':'current-password');$('loginBtn').textContent=state.modoAcceso==='registro'?'Registrar PIN e ingresar':'Ingresar';status('loginStatus',state.modoAcceso==='registro'?'Primer ingreso: crea un PIN personal de 4 a 8 dígitos.':'Escribe tu PIN.','success');$('pinInput').focus()}).catch(function(e){status('loginStatus',e.message,'error')})}
function ingresar(){var c=text($('cedulaInput').value).replace(/\D/g,''),pin=text($('pinInput').value);if(state.modoAcceso==='consulta'){consultarAcceso();return}if(state.modoAcceso==='registro'&&pin!==text($('pinConfirmInput').value)){status('loginStatus','Los PIN no coinciden.','error');return}var action=state.modoAcceso==='registro'?'REGISTRAR_PIN':'LOGIN';status('loginStatus','Ingresando...','');api(action,{cedula:c,pin:pin}).then(function(r){state.sesion=r.sesion;state.investigador={cedula:r.cedula,nombre:r.nombre};guardarSesion();$('salirBtn').hidden=false;cargarCarreras()}).catch(function(e){status('loginStatus',e.message,'error')})}
function cargarCarreras(){view('dashboard');api('LISTAR_CARRERAS',{}).then(function(r){state.investigador=r.investigador;state.carreras=r.carreras||[];$('investigadorNombre').textContent=state.investigador.nombre;$('totalPendientes').textContent=r.totalPendientes||0;pintarCarreras()}).catch(function(e){limpiarSesion();view('login');status('loginStatus',e.message,'error')})}
function pintarCarreras(){var q=norm($('buscarCarrera').value),rows=state.carreras.filter(function(x){return !q||norm(x.carrera).indexOf(q)>=0});$('carrerasBody').innerHTML=rows.length?rows.map(function(x){return '<tr><td><strong>'+esc(x.carrera)+'</strong></td><td>'+Number(x.cantidad||0)+'</td><td><button class="primary" data-carrera="'+esc(x.carrera)+'">Revisar</button></td></tr>'}).join(''):'<tr><td colspan="3" class="empty">No hay carreras pendientes.</td></tr>'}
function abrirCarrera(carrera){state.carreraActual=carrera;$('carreraTitulo').textContent=carrera;view('career');cargarPendientes()}
function cargarPendientes(){return api('LISTAR_PENDIENTES_CARRERA',{carrera:state.carreraActual}).then(function(r){state.pendientes=r.pendientes||[];pintarPendientes();return state.pendientes}).catch(function(e){alert(e.message);return[]})}
function pintarPendientes(){var q=norm($('buscarPendiente').value),rows=state.pendientes.filter(function(x){var base=norm([x.nombre,x.cedula,x.titulo1,x.titulo2,x.titulo3,x.tituloCoordinador].join(' '));return !q||base.indexOf(q)>=0});$('pendientesBody').innerHTML=rows.length?rows.map(function(x){var estado=x.tomado?(x.tomadoPorMi?'Continuar revisión':'Tomado por otro usuario'):'Disponible',action=x.tomado&&!x.tomadoPorMi?'<button disabled>Bloqueado</button>':'<button class="primary" data-envio="'+esc(x.id)+'">'+(x.tomadoPorMi?'Continuar':'Tomar revisión')+'</button>';return '<tr><td><strong>'+esc(x.nombre||'Sin nombre')+'</strong><small>'+esc(x.cedula)+'</small></td><td>'+esc(x.tipoTrabajoLabel)+'</td><td>'+esc(x.periodo||'-')+'</td><td><span class="pill '+(x.tomado?'busy':'')+'">'+estado+'</span></td><td>'+action+'</td></tr>'}).join(''):'<tr><td colspan="5" class="empty">No hay pendientes en esta carrera.</td></tr>'}
function tomar(id){api('TOMAR_REVISION',{envioId:id}).then(function(r){abrirRevision(r.envio)}).catch(function(e){alert(e.message);cargarPendientes()})}
function tituloModificado(){return Boolean(state.revision&&norm($('tituloFinalInput').value)!==norm(state.revision.tituloCoordinador))}
function actualizarAccionesRevision(){var activo=Boolean(state.revision),cambio=activo&&tituloModificado();$('aprobarBtn').disabled=!activo||cambio;$('corregirAprobarBtn').disabled=!activo||!cambio;$('devolverBtn').disabled=!activo}
function iniciarHeartbeat(){detenerHeartbeat();if(!state.revision)return;state.heartbeat=setInterval(function(){api('HEARTBEAT_REVISION',{envioId:state.revision.id}).catch(function(){detenerHeartbeat();status('reviewStatus','La reserva de esta revisión se perdió. Vuelve a la lista y tómala nuevamente.','error');actualizarAccionesRevision()})},45000)}
function detenerHeartbeat(){if(state.heartbeat){clearInterval(state.heartbeat);state.heartbeat=null}}
function cerrarResultadoModal(){var modal=$('resultadoModal');if(modal)modal.hidden=true;document.body.classList.remove('modal-open')}
function mostrarResultadoModal(accion,contexto,respuesta){
  var modal=$('resultadoModal'),icono=$('resultadoModalIcono'),titulo=$('resultadoModalTitulo'),estudiante=$('resultadoModalEstudiante'),mensaje=$('resultadoModalMensaje'),box=$('resultadoModalTituloBox'),final=$('resultadoModalTituloFinal');
  if(!modal)return;
  var config=accion==='DEVOLVER'
    ?{icon:'↩',clase:'is-returned',titulo:'Título devuelto al estudiante',mensaje:'La devolución quedó registrada correctamente. Cuando el estudiante reenvíe, el proceso volverá a Coordinación y luego a Investigación.',mostrarTitulo:false}
    :accion==='CORREGIR_APROBAR'
      ?{icon:'✓',clase:'is-corrected',titulo:'Título corregido y aprobado',mensaje:'La corrección quedó guardada y el título fue aprobado definitivamente.',mostrarTitulo:true}
      :{icon:'✓',clase:'',titulo:'Título aprobado',mensaje:'La aprobación final quedó registrada correctamente.',mostrarTitulo:true};
  icono.textContent=config.icon;icono.className='result-modal__icon '+config.clase;
  titulo.textContent=config.titulo;
  estudiante.textContent=contexto&&contexto.nombre?contexto.nombre:'';
  mensaje.textContent=respuesta&&respuesta.mensaje?respuesta.mensaje:config.mensaje;
  var tituloFinal=text(respuesta&&respuesta.tituloFinal||contexto&&contexto.tituloFinal||'');
  box.hidden=!config.mostrarTitulo;
  final.textContent=tituloFinal||'-';
  modal.hidden=false;document.body.classList.add('modal-open');
  setTimeout(function(){var focus=$('resultadoSiguienteBtn');if(focus)focus.focus()},0);
}
function abrirRevision(item){state.revision=item;view('review');$('revisionNombre').textContent=item.nombre||'-';$('revisionMeta').textContent=[item.carrera,item.periodo,item.tipoTrabajoLabel].filter(Boolean).join(' · ');$('tituloCoordinador').textContent=item.tituloCoordinador||'-';$('tituloFinalInput').value=item.tituloCoordinador||'';$('observacionInput').value='';$('postAction').hidden=true;status('reviewStatus','','');var comentario=text(item.comentarioCoordinador),box=$('comentarioCoordinadorBox');if(box)box.hidden=!comentario;if($('comentarioCoordinador'))$('comentarioCoordinador').textContent=comentario||'-';var historial=Array.isArray(item.historial)?item.historial:[],hbox=$('historialBox');if(hbox)hbox.hidden=!historial.length;if($('historialRevision'))$('historialRevision').innerHTML=historial.map(function(h){var titulo=h.tituloAntes&&h.tituloDespues&&norm(h.tituloAntes)!==norm(h.tituloDespues)?'<p><strong>Antes:</strong> '+esc(h.tituloAntes)+'</p><p><strong>Después:</strong> '+esc(h.tituloDespues)+'</p>':'';return '<article class="proposal"><small>'+esc([h.rol,h.accion,h.fecha].filter(Boolean).join(' · '))+'</small>'+titulo+(h.observacion?'<p>'+esc(h.observacion)+'</p>':'')+'</article>'}).join('');var fav=Number(item.tituloPreferidoNumero||0);$('propuestasGrid').innerHTML=[1,2,3].map(function(n){var t=item['titulo'+n]||'Sin título registrado';return '<article class="proposal '+(fav===n?'is-favorite':'')+'"><small>Propuesta '+n+(fav===n?' · Favorito del estudiante':'')+'</small><p>'+esc(t)+'</p><button type="button" class="secondary" data-usar-propuesta="'+n+'">Usar esta propuesta</button></article>'}).join('');actualizarAccionesRevision();iniciarHeartbeat()}
function liberarYVolver(){if(!state.revision){view('career');return}var id=state.revision.id;detenerHeartbeat();api('LIBERAR_REVISION',{envioId:id}).catch(function(){}).finally(function(){state.revision=null;view('career');cargarPendientes()})}
function resolver(accion){if(!state.revision)return;var cambio=tituloModificado();if(accion==='APROBAR'&&cambio){status('reviewStatus','El título fue modificado. Usa “Corregir y aprobar”.','error');return}if(accion==='CORREGIR_APROBAR'&&!cambio){status('reviewStatus','No hay cambios en el título. Usa “Aprobar sin cambios”.','error');return}var confirmacion=accion==='DEVOLVER'?'¿Devolver este caso al estudiante? Al reenviar deberá pasar nuevamente por Coordinación e Investigación.':accion==='CORREGIR_APROBAR'?'¿Guardar el título corregido y aprobarlo definitivamente? Esta acción finalizará el proceso.':'¿Aprobar sin cambios el título validado por Coordinación? Esta acción finalizará el proceso.';if(!window.confirm(confirmacion))return;var contexto={id:state.revision.id,nombre:state.revision.nombre||'',carrera:state.revision.carrera||'',tituloFinal:text($('tituloFinalInput').value)};var data={envioId:state.revision.id,accionRevision:accion,tituloFinal:contexto.tituloFinal,observacion:text($('observacionInput').value)};status('reviewStatus','Guardando revisión...','');['aprobarBtn','corregirAprobarBtn','devolverBtn'].forEach(function(id){$(id).disabled=true});api('RESOLVER_REVISION',data).then(function(r){detenerHeartbeat();status('reviewStatus',r.mensaje,'success');$('postAction').hidden=true;state.revision=null;actualizarAccionesRevision();mostrarResultadoModal(accion,contexto,r)}).catch(function(e){status('reviewStatus',e.message,'error');actualizarAccionesRevision()})}
function siguiente(){view('career');return cargarPendientes().then(function(rows){var next=(rows||[]).find(function(x){return !x.tomado||x.tomadoPorMi});if(next)return tomar(next.id);return cargarCarreras()})}
document.addEventListener('click',function(ev){var p=ev.target.closest('[data-usar-propuesta]');if(p&&state.revision){var n=Number(p.getAttribute('data-usar-propuesta')||0),t=state.revision['titulo'+n];if(t){$('tituloFinalInput').value=t;actualizarAccionesRevision()}return}var b=ev.target.closest('[data-carrera],[data-envio]');if(b&&b.hasAttribute('data-carrera'))abrirCarrera(b.getAttribute('data-carrera'));else if(b&&b.hasAttribute('data-envio'))tomar(b.getAttribute('data-envio'))});
$('loginForm').addEventListener('submit',function(e){e.preventDefault();ingresar()});
$('buscarCarrera').addEventListener('input',pintarCarreras);$('buscarPendiente').addEventListener('input',pintarPendientes);$('tituloFinalInput').addEventListener('input',actualizarAccionesRevision);
$('volverCarrerasBtn').addEventListener('click',cargarCarreras);$('cerrarRevisionBtn').addEventListener('click',liberarYVolver);
$('aprobarBtn').addEventListener('click',function(){resolver('APROBAR')});$('corregirAprobarBtn').addEventListener('click',function(){resolver('CORREGIR_APROBAR')});$('devolverBtn').addEventListener('click',function(){resolver('DEVOLVER')});
$('volverDespuesBtn').addEventListener('click',cargarCarreras);$('siguienteBtn').addEventListener('click',siguiente);
$('resultadoVolverBtn').addEventListener('click',function(){cerrarResultadoModal();cargarCarreras()});
$('resultadoSiguienteBtn').addEventListener('click',function(){cerrarResultadoModal();siguiente()});
$('salirBtn').addEventListener('click',function(){var revision=state.revision,job=revision?api('LIBERAR_REVISION',{envioId:revision.id}).catch(function(){}):Promise.resolve();detenerHeartbeat();state.revision=null;job.then(function(){return api('LOGOUT',{}).catch(function(){})}).finally(function(){limpiarSesion();$('salirBtn').hidden=true;view('login')})});
window.addEventListener('beforeunload',function(){if(!state.revision||!state.sesion)return;try{navigator.sendBeacon('/api/investigadores',new Blob([JSON.stringify({accion:'LIBERAR_REVISION',datos:{sesion:state.sesion,envioId:state.revision.id}})],{type:'application/json'}))}catch(e){}});
(function restore(){try{state.sesion=sessionStorage.getItem('investigacion_sesion')||'';var n=sessionStorage.getItem('investigacion_nombre')||'';if(state.sesion){state.investigador={nombre:n};$('salirBtn').hidden=false;cargarCarreras()}}catch(e){}})();
})(window,document);