(function(window,document){'use strict';
var state={sesion:'',investigador:null,carreras:[],carreraActual:'',pendientes:[],revision:null,heartbeat:null,modoAcceso:'consulta'};
function $(id){return document.getElementById(id)}
function text(v){return String(v==null?'':v).trim()}
function norm(v){return text(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function esc(v){return text(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function api(action,data){return fetch('/api/investigadores',{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-Titulos-App':'investigadores'},body:JSON.stringify({accion:action,datos:Object.assign({},data||{},state.sesion?{sesion:state.sesion}:{})})}).then(function(r){return r.json().then(function(j){if(!r.ok||j.ok===false)throw new Error(j.mensaje||'No se pudo completar la operación.');return j})})}
function status(id,msg,type){var el=$(id);if(!el)return;el.textContent=msg||'';el.className='status '+(type||'')}
function view(name){['login','dashboard','career','review'].forEach(function(v){var el=$(v+'View');if(el)el.hidden=v!==name})}
function guardarSesion(){try{sessionStorage.setItem('investigacion_sesion',state.sesion);sessionStorage.setItem('investigacion_nombre',state.investigador&&state.investigador.nombre||'')}catch(e){}}
function limpiarSesion(){state.sesion='';state.investigador=null;try{sessionStorage.removeItem('investigacion_sesion');sessionStorage.removeItem('investigacion_nombre')}catch(e){}}
function consultarAcceso(){var c=text($('cedulaInput').value).replace(/\D/g,'');if(c.length!==10){status('loginStatus','Ingresa una cédula válida.','error');return}status('loginStatus','Consultando acceso...','');api('CONSULTAR_ACCESO',{cedula:c}).then(function(r){if(!r.encontrado)throw new Error(r.mensaje||'No autorizado.');state.modoAcceso=r.requiereRegistroPin?'registro':'login';$('pinWrap').hidden=false;$('pinConfirmWrap').hidden=state.modoAcceso!=='registro';$('pinInput').setAttribute('autocomplete',state.modoAcceso==='registro'?'new-password':'current-password');$('loginBtn').textContent=state.modoAcceso==='registro'?'Registrar PIN e ingresar':'Ingresar';status('loginStatus',state.modoAcceso==='registro'?'Primer ingreso: crea un PIN personal de 4 a 8 dígitos.':'Escribe tu PIN.','success');$('pinInput').focus()}).catch(function(e){status('loginStatus',e.message,'error')})}
function ingresar(){var c=text($('cedulaInput').value).replace(/\D/g,''),pin=text($('pinInput').value);if(state.modoAcceso==='consulta'){consultarAcceso();return}if(state.modoAcceso==='registro'&&pin!==text($('pinConfirmInput').value)){status('loginStatus','Los PIN no coinciden.','error');return}var action=state.modoAcceso==='registro'?'REGISTRAR_PIN':'LOGIN';status('loginStatus','Ingresando...','');api(action,{cedula:c,pin:pin}).then(function(r){state.sesion=r.sesion;state.investigador={cedula:r.cedula,nombre:r.nombre};guardarSesion();$('salirBtn').hidden=false;cargarCarreras()}).catch(function(e){status('loginStatus',e.message,'error')})}
function cargarCarreras(){view('dashboard');api('LISTAR_CARRERAS',{}).then(function(r){state.investigador=r.investigador;state.carreras=r.carreras||[];$('investigadorNombre').textContent=state.investigador.nombre;$('totalPendientes').textContent=r.totalPendientes||0;pintarCarreras()}).catch(function(e){limpiarSesion();view('login');status('loginStatus',e.message,'error')})}
function pintarCarreras(){var q=norm($('buscarCarrera').value),rows=state.carreras.filter(function(x){return !q||norm(x.carrera).indexOf(q)>=0});$('carrerasBody').innerHTML=rows.length?rows.map(function(x){return '<tr><td><strong>'+esc(x.carrera)+'</strong></td><td>'+Number(x.cantidad||0)+'</td><td><button class="primary" data-carrera="'+esc(x.carrera)+'">Revisar</button></td></tr>'}).join(''):'<tr><td colspan="3" class="empty">No hay carreras pendientes.</td></tr>'}
function abrirCarrera(carrera){state.carreraActual=carrera;$('carreraTitulo').textContent=carrera;view('career');cargarPendientes()}
function cargarPendientes(){api('LISTAR_PENDIENTES_CARRERA',{carrera:state.carreraActual}).then(function(r){state.pendientes=r.pendientes||[];pintarPendientes()}).catch(function(e){alert(e.message)})}
function pintarPendientes(){var q=norm($('buscarPendiente').value),rows=state.pendientes.filter(function(x){var base=norm([x.nombre,x.cedula,x.titulo1,x.titulo2,x.titulo3,x.tituloCoordinador].join(' '));return !q||base.indexOf(q)>=0});$('pendientesBody').innerHTML=rows.length?rows.map(function(x){var estado=x.tomado?(x.tomadoPorMi?'Continuar revisión':'Tomado por otro usuario'):'Disponible',action=x.tomado&&!x.tomadoPorMi?'<button disabled>Bloqueado</button>':'<button class="primary" data-envio="'+esc(x.id)+'">'+(x.tomadoPorMi?'Continuar':'Tomar revisión')+'</button>';return '<tr><td><strong>'+esc(x.nombre||'Sin nombre')+'</strong><small>'+esc(x.cedula)+'</small></td><td>'+esc(x.tipoTrabajoLabel)+'</td><td>'+esc(x.periodo||'-')+'</td><td><span class="pill '+(x.tomado?'busy':'')+'">'+estado+'</span></td><td>'+action+'</td></tr>'}).join(''):'<tr><td colspan="5" class="empty">No hay pendientes en esta carrera.</td></tr>'}
function tomar(id){api('TOMAR_REVISION',{envioId:id}).then(function(r){abrirRevision(r.envio)}).catch(function(e){alert(e.message);cargarPendientes()})}
function iniciarHeartbeat(){detenerHeartbeat();if(!state.revision)return;state.heartbeat=setInterval(function(){api('HEARTBEAT_REVISION',{envioId:state.revision.id}).catch(function(){detenerHeartbeat()})},45000)}
function detenerHeartbeat(){if(state.heartbeat){clearInterval(state.heartbeat);state.heartbeat=null}}
function abrirRevision(item){state.revision=item;view('review');$('revisionNombre').textContent=item.nombre||'-';$('revisionMeta').textContent=[item.carrera,item.periodo,item.tipoTrabajoLabel].filter(Boolean).join(' · ');$('tituloCoordinador').textContent=item.tituloCoordinador||'-';$('tituloFinalInput').value=item.tituloCoordinador||'';$('observacionInput').value='';$('postAction').hidden=true;status('reviewStatus','','');var fav=Number(item.tituloPreferidoNumero||0);$('propuestasGrid').innerHTML=[1,2,3].map(function(n){var t=item['titulo'+n]||'Sin título registrado';return '<article class="proposal '+(fav===n?'is-favorite':'')+'"><small>Propuesta '+n+(fav===n?' · Favorito del estudiante':'')+'</small><p>'+esc(t)+'</p></article>'}).join('');iniciarHeartbeat()}
function liberarYVolver(){if(!state.revision){view('career');return}var id=state.revision.id;detenerHeartbeat();api('LIBERAR_REVISION',{envioId:id}).catch(function(){}).finally(function(){state.revision=null;view('career');cargarPendientes()})}
function resolver(accion){if(!state.revision)return;var data={envioId:state.revision.id,accionRevision:accion,tituloFinal:text($('tituloFinalInput').value),observacion:text($('observacionInput').value)};status('reviewStatus','Guardando revisión...','');['aprobarBtn','corregirAprobarBtn','devolverBtn'].forEach(function(id){$(id).disabled=true});api('RESOLVER_REVISION',data).then(function(r){detenerHeartbeat();status('reviewStatus',r.mensaje,'success');$('postAction').hidden=false;state.revision=null}).catch(function(e){status('reviewStatus',e.message,'error')}).finally(function(){['aprobarBtn','corregirAprobarBtn','devolverBtn'].forEach(function(id){$(id).disabled=false})})}
function siguiente(){view('career');cargarPendientes();setTimeout(function(){var next=state.pendientes.find(function(x){return !x.tomado||x.tomadoPorMi});if(next)tomar(next.id);else cargarCarreras()},350)}
document.addEventListener('click',function(ev){var b=ev.target.closest('[data-carrera],[data-envio]');if(b&&b.hasAttribute('data-carrera'))abrirCarrera(b.getAttribute('data-carrera'));else if(b&&b.hasAttribute('data-envio'))tomar(b.getAttribute('data-envio'))});
$('loginForm').addEventListener('submit',function(e){e.preventDefault();ingresar()});
$('buscarCarrera').addEventListener('input',pintarCarreras);$('buscarPendiente').addEventListener('input',pintarPendientes);
$('volverCarrerasBtn').addEventListener('click',cargarCarreras);$('cerrarRevisionBtn').addEventListener('click',liberarYVolver);
$('aprobarBtn').addEventListener('click',function(){resolver('APROBAR')});$('corregirAprobarBtn').addEventListener('click',function(){resolver('CORREGIR_APROBAR')});$('devolverBtn').addEventListener('click',function(){resolver('DEVOLVER')});
$('volverDespuesBtn').addEventListener('click',cargarCarreras);$('siguienteBtn').addEventListener('click',siguiente);
$('salirBtn').addEventListener('click',function(){if(state.revision)liberarYVolver();limpiarSesion();$('salirBtn').hidden=true;view('login')});
window.addEventListener('beforeunload',function(){if(!state.revision||!state.sesion)return;try{navigator.sendBeacon('/api/investigadores',new Blob([JSON.stringify({accion:'LIBERAR_REVISION',datos:{sesion:state.sesion,envioId:state.revision.id}})],{type:'application/json'}))}catch(e){}});
(function restore(){try{state.sesion=sessionStorage.getItem('investigacion_sesion')||'';var n=sessionStorage.getItem('investigacion_nombre')||'';if(state.sesion){state.investigador={nombre:n};$('salirBtn').hidden=false;cargarCarreras()}}catch(e){}})();
})(window,document);